<?php
require_once __DIR__.'/../../config/config.php';
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/auth.php';
require_once __DIR__.'/../../includes/host-structure.php';
requireRole(['ADMIN_ACCUEIL']);
if(!contextHostEnabled())exit("Cet établissement n'est pas une structure d'accueil.");
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$eid=(int)($_SESSION['etablissement_id']??0);$cfg=hostStructureConfig($pdo,$eid);$defaults=hostStructureDefaults();
$pageTitle="Structure d'accueil";$activePage='host-structure-config';require_once __DIR__.'/../../includes/app-header.php';
?>
<style>.host-config-grid{display:grid;gap:14px}.host-config-card{background:#fff;border:1px solid #e7ebf0;border-radius:14px;padding:18px}.host-config-code{font-size:11px;font-weight:700;color:#64748b;letter-spacing:.05em}.host-config-preview{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:10px;padding:10px 12px}</style>
<main class="dashboard-content">
<div class="stagia-page-head"><div><h1>Structure d’accueil</h1><p>Adaptez l’organisation de l’hôpital sans modifier les codes techniques STAGIA.</p></div></div>
<div class="alert alert-info border-0 mb-4"><i class="bi bi-info-circle me-1"></i>Organisation recommandée : <strong>Département → Service → Unité</strong>. Chaque niveau peut être renommé ou retiré. Retirer ne supprime jamais l’historique.</div>
<div class="host-config-grid">
<?php foreach($cfg as $code=>$r):$def=$defaults[$code]; ?>
<div class="host-config-card" data-code="<?=htmlspecialchars($code)?>">
<div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div><div class="host-config-code"><?=htmlspecialchars($code)?></div><h5 class="mb-1"><?=htmlspecialchars($r['label_plural'])?></h5><small class="text-muted">STAGIA : <?=htmlspecialchars($def['label_singular'])?> / <?=htmlspecialchars($def['label_plural'])?></small></div><span class="badge <?=!empty($r['actif'])?'bg-success-subtle text-success':'bg-secondary-subtle text-secondary'?>"><?=!empty($r['actif'])?'Utilisé':'Retiré'?></span></div>
<div class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Nom singulier *</label><input class="form-control singular" maxlength="100" value="<?=htmlspecialchars($r['label_singular'])?>"></div><div class="col-md-4"><label class="form-label">Nom pluriel *</label><input class="form-control plural" maxlength="100" value="<?=htmlspecialchars($r['label_plural'])?>"></div><div class="col-md-2"><label class="form-label">Ordre</label><input type="number" class="form-control order" min="0" max="999" value="<?=(int)$r['sort_order']?>"></div><div class="col-md-2"><div class="host-config-preview"><small class="text-muted d-block">Menu</small><strong class="preview"><?=htmlspecialchars($r['label_plural'])?></strong></div></div></div>
<div class="d-flex flex-wrap gap-2 mt-3"><button type="button" class="btn btn-primary-stagia save-config"><i class="bi bi-check-lg me-1"></i>Enregistrer</button><?php if(!empty($r['actif'])): ?><button type="button" class="btn btn-outline-danger toggle-config" data-next="0"><i class="bi bi-dash-circle me-1"></i>Retirer</button><?php else: ?><button type="button" class="btn btn-outline-success toggle-config" data-next="1"><i class="bi bi-plus-circle me-1"></i>Réactiver</button><?php endif; ?><button type="button" class="btn btn-light border reset-config"><i class="bi bi-arrow-counterclockwise me-1"></i>Restaurer STAGIA</button></div>
</div>
<?php endforeach; ?>
</div></main>
<script>document.addEventListener('DOMContentLoaded',()=>{const BASE_URL='<?=BASE_URL?>',CSRF='<?=htmlspecialchars($_SESSION['csrf'],ENT_QUOTES)?>';document.querySelectorAll('.host-config-card').forEach(card=>{const code=card.dataset.code,s=card.querySelector('.singular'),p=card.querySelector('.plural'),o=card.querySelector('.order'),preview=card.querySelector('.preview'),save=card.querySelector('.save-config'),toggle=card.querySelector('.toggle-config'),reset=card.querySelector('.reset-config');p.oninput=()=>preview.textContent=p.value||'—';async function send(extra={}){const fd=new FormData();fd.append('csrf',CSRF);fd.append('entity_code',code);fd.append('label_singular',s.value.trim());fd.append('label_plural',p.value.trim());fd.append('sort_order',o.value||0);fd.append('actif',extra.actif??(toggle?.dataset.next==='1'?0:1));if(extra.reset)fd.append('reset','1');return STAGIA.post(BASE_URL+'/actions/espace-hopital/structure-config-save.php',fd)}save.onclick=async()=>{STAGIA.loading(save,true);try{const r=await send({actif:toggle?.dataset.next==='0'?1:0});STAGIA.toast(r.message);setTimeout(()=>location.reload(),300)}catch(e){STAGIA.toast(e.message,'danger')}finally{STAGIA.loading(save,false)}};if(toggle)toggle.onclick=async()=>{const next=Number(toggle.dataset.next);if(!STAGIA.confirm(next?'Réactiver ce niveau ?':'Retirer ce niveau de la structure active ?'))return;try{const r=await send({actif:next});STAGIA.toast(r.message);setTimeout(()=>location.reload(),300)}catch(e){STAGIA.toast(e.message,'danger')}};reset.onclick=async()=>{if(!STAGIA.confirm('Restaurer le nom et le statut STAGIA ?'))return;try{const r=await send({reset:1});STAGIA.toast(r.message);setTimeout(()=>location.reload(),300)}catch(e){STAGIA.toast(e.message,'danger')}}})});</script>
<?php require_once __DIR__.'/../../includes/app-footer.php'; ?>
