<?php
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/permissions.php';
require_once __DIR__.'/../../includes/ajax.php';
require_once __DIR__.'/../../includes/academic-unit-sync.php';
requireAjaxRole(['SUPER_ADMIN']);verifyAjaxCsrf();
$id=(int)($_POST['id']??0);$action=strtoupper(trim((string)($_POST['action']??'')));$comment=trim((string)($_POST['comment']??''));if(!$id||!in_array($action,['APPROVE_LOCAL','INTEGRATE_NATIONAL','REFUSE'],true))jsonResponse(false,'Action invalide.',[],422);
try{
$pdo->beginTransaction();$s=$pdo->prepare("SELECT f.*,eas.source_template_id FROM facultes f JOIN etablissement_academic_settings eas ON eas.etablissement_id=f.etablissement_id WHERE f.id=? AND f.ajoute_localement=1 LIMIT 1 FOR UPDATE");$s->execute([$id]);$f=$s->fetch(PDO::FETCH_ASSOC);if(!$f)throw new RuntimeException('Ajout local introuvable.');$uid=(int)($_SESSION['user_id']??0)?:null;
if($action==='APPROVE_LOCAL'){$pdo->prepare("UPDATE facultes SET validation_statut='VALIDE_LOCAL',actif=1,reviewed_by_user_id=?,reviewed_at=NOW(),review_comment=? WHERE id=?")->execute([$uid,$comment?:null,$id]);$message='Unité validée pour cet établissement uniquement.';}
if($action==='REFUSE'){if($comment==='')throw new RuntimeException('Le motif du refus est obligatoire.');$pdo->prepare("UPDATE facultes SET validation_statut='REFUSE',actif=0,reviewed_by_user_id=?,reviewed_at=NOW(),review_comment=? WHERE id=?")->execute([$uid,$comment,$id]);$message='Unité locale refusée.';}
if($action==='INTEGRATE_NATIONAL'){$templateId=(int)$f['source_template_id'];if(!$templateId)throw new RuntimeException('Aucun modèle source.');$parentTpl=null;if((int)($f['parent_id']??0)){$s=$pdo->prepare("SELECT source_template_unit_id FROM facultes WHERE id=? AND etablissement_id=? LIMIT 1");$s->execute([(int)$f['parent_id'],(int)$f['etablissement_id']]);$parentTpl=(int)$s->fetchColumn()?:null;if(!$parentTpl)throw new RuntimeException("Intégrez d'abord l'unité parente au référentiel national.");}$s=$pdo->prepare("SELECT 1 FROM academic_structure_template_unit_types WHERE template_id=? AND type_unite=? AND actif=1 LIMIT 1");$s->execute([$templateId,$f['type_unite']]);if(!$s->fetchColumn())throw new RuntimeException("Ce type d'unité n'est pas autorisé par le modèle.");$code=makeAcademicTemplateUnitCode($pdo,$templateId,$f['nom']);$s=$pdo->prepare("SELECT COALESCE(MAX(ordre),0)+10 FROM academic_template_units WHERE template_id=?");$s->execute([$templateId]);$ordre=(int)$s->fetchColumn();$pdo->prepare("INSERT INTO academic_template_units(template_id,parent_id,type_unite,code,nom,ordre,actif) VALUES(?,?,?,?,?,?,1)")->execute([$templateId,$parentTpl,$f['type_unite'],$code,$f['nom'],$ordre]);$tid=(int)$pdo->lastInsertId();$pdo->prepare("UPDATE facultes SET source_template_unit_id=?,code=?,validation_statut='INTEGRE_REFERENTIEL',actif=1,reviewed_by_user_id=?,reviewed_at=NOW(),review_comment=? WHERE id=?")->execute([$tid,$code,$uid,$comment?:null,$id]);$pdo->prepare("UPDATE academic_structure_templates SET version_no=version_no+1 WHERE id=?")->execute([$templateId]);syncAcademicTemplateUnit($pdo,$templateId,$tid);$message='Unité intégrée au référentiel national et propagée.';}
$pdo->commit();jsonResponse(true,$message);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();jsonResponse(false,$e->getMessage(),[],422);}
