<?php
require_once __DIR__.'/../../config/config.php';
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/auth.php';
require_once __DIR__.'/../../includes/stage-feedback.php';

requireRole(['ADMIN_ACCUEIL','COORDINATEUR_STAGES','ENCADREUR','EVALUATEUR_CLINIQUE','CHEF_SERVICE','AUTORITE_HOSPITALIERE']);
if(!contextHostEnabled()||!feedbackHostCanView()){http_response_code(403);exit('Accès refusé.');}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$pageTitle='Feedback & observations';$activePage='hospital-feedbacks';
require_once __DIR__.'/../../includes/app-header.php';
?>
<style>
.feedback-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.feedback-kpi,.feedback-card{background:#fff;border:1px solid #e7ebf0;border-radius:14px}.feedback-kpi{padding:16px}.feedback-kpi small{display:block;color:#64748b;font-size:11px;text-transform:uppercase}.feedback-kpi strong{font-size:26px}.feedback-card{padding:17px}.feedback-meta{font-size:12px;color:#64748b}.feedback-text{white-space:pre-line}.type-OBSERVATION{background:#eef2ff;color:#4338ca}.type-ENCOURAGEMENT{background:#ecfdf5;color:#047857}.type-A_AMELIORER{background:#fff7ed;color:#c2410c}.type-AVERTISSEMENT{background:#fef2f2;color:#b91c1c}@media(max-width:1050px){.feedback-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.feedback-kpis{grid-template-columns:1fr}}
</style>
<main class="dashboard-content">
<div class="stagia-page-head"><div><h1>Feedback & observations</h1><p>Consignez les retours de suivi sans les confondre avec l'évaluation officielle.</p></div><button id="addBtn" class="btn btn-primary-stagia d-none"><i class="bi bi-plus-lg me-1"></i> Nouveau feedback</button></div>
<div class="alert alert-light border"><i class="bi bi-chat-left-text text-primary me-1"></i> Un feedback peut être <strong>visible par le stagiaire</strong> ou conservé comme <strong>note interne</strong>. Après publication, il est verrouillé ; l'évaluation reste un processus distinct.</div>
<div class="feedback-kpis mb-4"><div class="feedback-kpi"><small>Total</small><strong id="kTotal">0</strong></div><div class="feedback-kpi"><small>Brouillons</small><strong id="kDraft">0</strong></div><div class="feedback-kpi"><small>Publiés</small><strong id="kPublished">0</strong></div><div class="feedback-kpi"><small>À améliorer</small><strong id="kImprove">0</strong></div><div class="feedback-kpi"><small>Avertissements</small><strong id="kWarning">0</strong></div></div>
<div class="feedback-card mb-3"><div class="row g-2"><div class="col-lg-4"><input id="search" class="form-control" placeholder="Rechercher un feedback ou un stagiaire..."></div><div class="col-lg-3"><select id="studentFilter" class="form-select"><option value="">Tous les stagiaires</option></select></div><div class="col-lg-2"><select id="typeFilter" class="form-select"><option value="">Tous les types</option><option value="OBSERVATION">Observation</option><option value="ENCOURAGEMENT">Encouragement</option><option value="A_AMELIORER">À améliorer</option><option value="AVERTISSEMENT">Avertissement</option></select></div><div class="col-lg-2"><select id="statusFilter" class="form-select"><option value="">Tous les statuts</option><option value="BROUILLON">Brouillons</option><option value="PUBLIE">Publiés</option><option value="ARCHIVE">Archivés</option></select></div><div class="col-lg-1"><button id="refreshBtn" class="btn btn-light border w-100" title="Actualiser"><i class="bi bi-arrow-clockwise"></i></button></div></div></div>
<div id="feedbackList"><div class="feedback-card text-center text-muted py-5">Chargement...</div></div>
</main>

<div class="modal fade" id="feedbackModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="feedbackForm">
<div class="modal-header"><div><h5 class="modal-title" id="feedbackModalTitle">Nouveau feedback</h5><small class="text-muted">Retour de supervision du stagiaire.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="id" id="feedbackId">
<div class="row g-3"><div class="col-12"><label class="form-label">Stagiaire / affectation *</label><select name="assignment_id" id="assignment" class="form-select" required></select></div><div class="col-md-6"><label class="form-label">Rotation</label><select name="rotation_id" id="rotation" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Date *</label><input type="date" name="date_feedback" id="feedbackDate" class="form-control" required></div><div class="col-md-6"><label class="form-label">Type *</label><select name="type_feedback" id="feedbackType" class="form-select" required><option value="OBSERVATION">Observation</option><option value="ENCOURAGEMENT">Encouragement</option><option value="A_AMELIORER">À améliorer</option><option value="AVERTISSEMENT">Avertissement</option></select></div><div class="col-md-6"><label class="form-label">Titre</label><input name="titre" id="title" maxlength="180" class="form-control" placeholder="Ex. Présentation des cas cliniques"></div><div class="col-12"><label class="form-label">Commentaire *</label><textarea name="commentaire" id="comment" rows="5" maxlength="5000" class="form-control" required></textarea></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="visible_stagiaire" id="visible" value="1" checked><label class="form-check-label" for="visible"><strong>Visible par le stagiaire après publication</strong></label></div><small class="text-muted">Décochez pour conserver une note interne de supervision.</small></div></div></div>
<div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Annuler</button><button id="saveBtn" class="btn btn-primary-stagia"><i class="bi bi-check-lg me-1"></i>Enregistrer</button></div></form></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
const BASE='<?=BASE_URL?>',CSRF='<?=htmlspecialchars($_SESSION['csrf'])?>',$=id=>document.getElementById(id),esc=STAGIA.escape,modal=new bootstrap.Modal($('feedbackModal'));
let data={items:[],students:[],assignments:[],rotations:[],can_manage:false},timer;
const labels={OBSERVATION:'Observation',ENCOURAGEMENT:'Encouragement',A_AMELIORER:'À améliorer',AVERTISSEMENT:'Avertissement'},statusLabels={BROUILLON:'Brouillon',PUBLIE:'Publié',ARCHIVE:'Archivé'};
function dateFr(v){if(!v)return '—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v;}
function typeBadge(t){return `<span class="badge type-${esc(t)}">${esc(labels[t]||t)}</span>`;}
function statusBadge(s){const c={BROUILLON:'bg-secondary-subtle text-secondary',PUBLIE:'bg-success-subtle text-success',ARCHIVE:'bg-dark-subtle text-dark'}[s]||'bg-light text-dark';return `<span class="badge ${c}">${esc(statusLabels[s]||s)}</span>`;}
function actions(x){if(!data.can_manage||!x.mine)return '<span class="text-muted small">Lecture seule</span>';const a=[];if(x.statut==='BROUILLON'){a.push(`<button class="btn btn-sm btn-outline-primary edit" data-id="${x.id}" title="Modifier"><i class="bi bi-pencil"></i></button>`);a.push(`<button class="btn btn-sm btn-outline-success status" data-id="${x.id}" data-action="PUBLISH" title="Publier"><i class="bi bi-send-check"></i></button>`);}if(x.statut!=='ARCHIVE')a.push(`<button class="btn btn-sm btn-outline-secondary status" data-id="${x.id}" data-action="ARCHIVE" title="Archiver"><i class="bi bi-archive"></i></button>`);return `<div class="btn-group btn-group-sm">${a.join('')}</div>`;}
function render(){const list=data.items||[];$('feedbackList').innerHTML=list.length?list.map(x=>`<div class="feedback-card mb-2"><div class="d-flex justify-content-between gap-3 flex-wrap"><div class="flex-grow-1"><div class="d-flex gap-2 align-items-center flex-wrap"><h5 class="mb-0">${esc(x.titre||labels[x.type_feedback]||'Feedback')}</h5>${typeBadge(x.type_feedback)}${statusBadge(x.statut)}<span class="badge ${Number(x.visible_stagiaire)?'bg-primary-subtle text-primary':'bg-light text-dark border'}">${Number(x.visible_stagiaire)?'Visible stagiaire':'Note interne'}</span></div><div class="mt-1"><strong>${esc(x.student_name)}</strong> <span class="text-muted">${esc(x.stagia_code||'')}</span></div><div class="feedback-meta mt-1"><i class="bi bi-calendar3 me-1"></i>${dateFr(x.date_feedback)}${x.unit_name?` · <i class="bi bi-geo-alt me-1"></i>${esc(x.unit_name)} · Rotation ${Number(x.sequence_no)||''}`:''}${x.author_name?` · <i class="bi bi-person me-1"></i>${esc(x.author_name)}`:''}</div><p class="feedback-text mt-2 mb-0">${esc(x.commentaire)}</p></div><div>${actions(x)}</div></div></div>`).join(''):'<div class="feedback-card text-center text-muted py-5">Aucun feedback.</div>';document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editFeedback(Number(b.dataset.id)));document.querySelectorAll('.status').forEach(b=>b.onclick=()=>changeStatus(Number(b.dataset.id),b.dataset.action));}
function fillFilters(){const old=$('studentFilter').value;$('studentFilter').innerHTML='<option value="">Tous les stagiaires</option>'+data.students.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.stagia_code||'')}</option>`).join('');$('studentFilter').value=old;$('addBtn').classList.toggle('d-none',!data.can_manage);}
async function load(){const q=new URLSearchParams();if($('search').value.trim())q.set('search',$('search').value.trim());if($('statusFilter').value)q.set('status',$('statusFilter').value);if($('typeFilter').value)q.set('type',$('typeFilter').value);if($('studentFilter').value)q.set('student_id',$('studentFilter').value);try{const r=await STAGIA.request(BASE+'/actions/espace-hopital/feedback-list.php?'+q);data=r.data||data;const s=data.stats||{};$('kTotal').textContent=s.total||0;$('kDraft').textContent=s.brouillons||0;$('kPublished').textContent=s.publies||0;$('kImprove').textContent=s.a_ameliorer||0;$('kWarning').textContent=s.avertissements||0;fillFilters();render();}catch(e){STAGIA.toast(e.message,'danger');}}
function updateRotations(){const aid=Number($('assignment').value)||0;$('rotation').innerHTML='<option value="">Feedback général du stage</option>'+data.rotations.filter(r=>Number(r.assignment_id)===aid).map(r=>`<option value="${r.id}">${esc(r.unit_name||'Rotation')} · ${dateFr(r.date_debut)} → ${dateFr(r.date_fin)}</option>`).join('');}
function openCreate(){$('feedbackForm').reset();$('feedbackId').value='';$('feedbackModalTitle').textContent='Nouveau feedback';$('assignment').disabled=false;$('assignment').innerHTML='<option value="">Sélectionner...</option>'+data.assignments.map(a=>`<option value="${a.assignment_id}">${esc(a.student_name)} · ${esc(a.stagia_code||'')}</option>`).join('');$('feedbackDate').value=new Date().toISOString().slice(0,10);$('visible').checked=true;updateRotations();modal.show();}
function editFeedback(id){const x=data.items.find(v=>Number(v.id)===id);if(!x||x.statut!=='BROUILLON'||!x.mine)return;$('feedbackForm').reset();$('feedbackId').value=x.id;$('feedbackModalTitle').textContent='Modifier le feedback';$('assignment').innerHTML=`<option value="${x.assignment_id}">${esc(x.student_name)} · ${esc(x.stagia_code||'')}</option>`;$('assignment').value=x.assignment_id;$('assignment').disabled=true;updateRotations();$('rotation').value=x.rotation_id||'';$('feedbackDate').value=x.date_feedback||'';$('feedbackType').value=x.type_feedback||'OBSERVATION';$('title').value=x.titre||'';$('comment').value=x.commentaire||'';$('visible').checked=Number(x.visible_stagiaire)===1;modal.show();}
$('feedbackForm').onsubmit=async e=>{e.preventDefault();STAGIA.loading($('saveBtn'),true);try{const fd=new FormData(e.currentTarget);if($('assignment').disabled)fd.set('assignment_id',data.items.find(v=>Number(v.id)===Number($('feedbackId').value))?.assignment_id||'');const url=$('feedbackId').value?BASE+'/actions/espace-hopital/feedback-update.php':BASE+'/actions/espace-hopital/feedback-store.php';const r=await STAGIA.post(url,fd);STAGIA.toast(r.message);modal.hide();await load();}catch(e){STAGIA.toast(e.message,'danger');}finally{STAGIA.loading($('saveBtn'),false);}};
async function changeStatus(id,action){const msg=action==='PUBLISH'?'Publier ce feedback ? Il sera ensuite verrouillé.':'Archiver ce feedback ?';if(!STAGIA.confirm(msg))return;const fd=new FormData();fd.append('csrf',CSRF);fd.append('id',id);fd.append('action',action);try{const r=await STAGIA.post(BASE+'/actions/espace-hopital/feedback-status.php',fd);STAGIA.toast(r.message);await load();}catch(e){STAGIA.toast(e.message,'danger');}}
$('assignment').onchange=updateRotations;$('addBtn').onclick=openCreate;$('refreshBtn').onclick=load;$('studentFilter').onchange=load;$('typeFilter').onchange=load;$('statusFilter').onchange=load;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,300);};load();
});
</script>
<?php require_once __DIR__.'/../../includes/app-footer.php'; ?>
