<?php
require_once __DIR__.'/../../config/config.php';
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/auth.php';
require_once __DIR__.'/../../includes/stage-task.php';

requireRole(['ADMIN_ACCUEIL','COORDINATEUR_STAGES','ENCADREUR','EVALUATEUR_CLINIQUE','AUTORITE_HOSPITALIERE']);
if(!contextHostEnabled()||!taskHostCanView()){http_response_code(403);exit('Accès refusé.');}
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));

$pageTitle='Tâches & progression';$activePage='hospital-tasks';
require_once __DIR__.'/../../includes/app-header.php';
?>
<style>
.task-kpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.task-kpi,.task-card{background:#fff;border:1px solid #e7ebf0;border-radius:14px}.task-kpi{padding:16px}.task-kpi small{display:block;color:#64748b;font-size:11px;text-transform:uppercase}.task-kpi strong{font-size:26px}.task-card{padding:16px}.task-progress{height:7px}.task-meta{font-size:12px;color:#64748b}.priority-URGENTE{color:#dc3545}.priority-HAUTE{color:#fd7e14}.priority-NORMALE{color:#0d6efd}.priority-BASSE{color:#6c757d}@media(max-width:1000px){.task-kpis{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.task-kpis{grid-template-columns:1fr}}
</style>
<main class="dashboard-content">
<div class="stagia-page-head"><div><h1>Tâches & progression</h1><p>Suivez l'exécution réelle du plan de formation pour chaque stagiaire.</p></div><button id="addBtn" class="btn btn-primary-stagia d-none"><i class="bi bi-plus-lg me-1"></i> Nouvelle tâche</button></div>
<div class="alert alert-light border"><i class="bi bi-info-circle text-primary me-1"></i> Le stagiaire démarre et termine sa tâche. L'encadreur la <strong>valide</strong> ou la renvoie <strong>à revoir</strong>. La progression est calculée uniquement sur les tâches validées.</div>
<div class="task-kpis mb-4"><div class="task-kpi"><small>Total</small><strong id="kTotal">0</strong></div><div class="task-kpi"><small>À faire</small><strong id="kTodo">0</strong></div><div class="task-kpi"><small>En cours</small><strong id="kDoing">0</strong></div><div class="task-kpi"><small>Terminées</small><strong id="kDone">0</strong></div><div class="task-kpi"><small>Validées</small><strong id="kValid">0</strong></div></div>
<div class="task-card mb-3"><div class="row g-2"><div class="col-lg-5"><input id="search" class="form-control" placeholder="Rechercher une tâche ou un stagiaire..."></div><div class="col-lg-3"><select id="studentFilter" class="form-select"><option value="">Tous les stagiaires</option></select></div><div class="col-lg-2"><select id="statusFilter" class="form-select"><option value="">Tous les statuts</option><option value="A_FAIRE">À faire</option><option value="EN_COURS">En cours</option><option value="TERMINEE">Terminées</option><option value="A_REVOIR">À revoir</option><option value="VALIDEE">Validées</option><option value="ANNULEE">Annulées</option></select></div><div class="col-lg-2"><button id="refreshBtn" class="btn btn-light border w-100"><i class="bi bi-arrow-clockwise me-1"></i>Actualiser</button></div></div></div>
<div id="progressWrap" class="mb-3"></div>
<div id="taskList"><div class="task-card text-center text-muted py-5">Chargement...</div></div>
</main>

<div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form id="taskForm">
<div class="modal-header"><div><h5 class="modal-title" id="taskModalTitle">Nouvelle tâche</h5><small class="text-muted">Tâche individuelle du stagiaire.</small></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><input type="hidden" name="id" id="taskId">
<div class="row g-3"><div class="col-12"><label class="form-label">Stagiaire / affectation *</label><select name="assignment_id" id="assignment" class="form-select" required></select></div><div class="col-md-6"><label class="form-label">Rotation</label><select name="rotation_id" id="rotation" class="form-select"></select></div><div class="col-md-6"><label class="form-label">Élément du plan publié</label><select name="training_plan_item_id" id="planItem" class="form-select"></select></div><div class="col-12"><label class="form-label">Titre *</label><input name="titre" id="title" class="form-control" maxlength="200" required></div><div class="col-12"><label class="form-label">Description</label><textarea name="description" id="description" rows="3" class="form-control"></textarea></div><div class="col-md-6"><label class="form-label">Priorité</label><select name="priorite" id="priority" class="form-select"><option value="BASSE">Basse</option><option value="NORMALE" selected>Normale</option><option value="HAUTE">Haute</option><option value="URGENTE">Urgente</option></select></div><div class="col-md-6"><label class="form-label">Échéance</label><input type="date" name="date_echeance" id="due" class="form-control"></div></div></div>
<div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Annuler</button><button id="saveBtn" class="btn btn-primary-stagia"><i class="bi bi-check-lg me-1"></i>Enregistrer</button></div></form></div></div></div>

<script>
document.addEventListener('DOMContentLoaded',()=>{
const BASE='<?=BASE_URL?>',CSRF='<?=htmlspecialchars($_SESSION['csrf'])?>',$=id=>document.getElementById(id),esc=STAGIA.escape,modal=new bootstrap.Modal($('taskModal'));
let data={items:[],students:[],assignments:[],rotations:[],plan_items:[],can_manage:false},timer;
const labels={A_FAIRE:'À faire',EN_COURS:'En cours',TERMINEE:'Terminée',A_REVOIR:'À revoir',VALIDEE:'Validée',ANNULEE:'Annulée'};
const classes={A_FAIRE:'bg-secondary-subtle text-secondary',EN_COURS:'bg-primary-subtle text-primary',TERMINEE:'bg-info-subtle text-info',A_REVOIR:'bg-warning-subtle text-warning',VALIDEE:'bg-success-subtle text-success',ANNULEE:'bg-danger-subtle text-danger'};
function dateFr(v){if(!v)return '—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v;}
function badge(s){return `<span class="badge ${classes[s]||'bg-light text-dark'}">${esc(labels[s]||s)}</span>`;}
function progress(){const st=data.students||[];$('progressWrap').innerHTML=st.length?`<div class="row g-2">${st.map(x=>`<div class="col-lg-4"><div class="task-card"><div class="d-flex justify-content-between"><div><strong>${esc(x.name)}</strong><small class="d-block text-muted">${esc(x.stagia_code||'')}</small></div><strong>${Number(x.progress)||0}%</strong></div><div class="progress task-progress mt-2"><div class="progress-bar" style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></div></div><small class="text-muted">${Number(x.validated)||0}/${Number(x.total)||0} tâche(s) validée(s)</small></div></div>`).join('')}</div>`:'';}
function actions(x){if(!data.can_manage)return '<span class="text-muted small">Lecture seule</span>';let a=[];if(['A_FAIRE','A_REVOIR'].includes(x.statut))a.push(`<button class="btn btn-sm btn-outline-primary edit" data-id="${x.id}" title="Modifier"><i class="bi bi-pencil"></i></button>`);if(x.statut==='TERMINEE'){a.push(`<button class="btn btn-sm btn-outline-success status" data-id="${x.id}" data-action="VALIDATE" title="Valider"><i class="bi bi-check2-circle"></i></button>`);a.push(`<button class="btn btn-sm btn-outline-warning status" data-id="${x.id}" data-action="REVIEW" title="À revoir"><i class="bi bi-arrow-repeat"></i></button>`);}if(!['VALIDEE','ANNULEE'].includes(x.statut))a.push(`<button class="btn btn-sm btn-outline-danger status" data-id="${x.id}" data-action="CANCEL" title="Annuler"><i class="bi bi-x-circle"></i></button>`);return `<div class="btn-group btn-group-sm">${a.join('')}</div>`;}
function render(){const list=data.items||[];$('taskList').innerHTML=list.length?list.map(x=>`<div class="task-card mb-2"><div class="d-flex justify-content-between gap-3 flex-wrap"><div class="flex-grow-1"><div class="d-flex gap-2 align-items-center flex-wrap"><h5 class="mb-0">${esc(x.titre)}</h5>${badge(x.statut)}<span class="task-meta priority-${esc(x.priorite)}"><i class="bi bi-flag me-1"></i>${esc(x.priorite)}</span></div><div class="mt-1"><strong>${esc(x.student_name)}</strong> <span class="text-muted">${esc(x.stagia_code||'')}</span></div><div class="task-meta mt-1">${x.unit_name?`<i class="bi bi-geo-alt me-1"></i>${esc(x.unit_name)} · Rotation ${Number(x.sequence_no)||''} · `:''}<i class="bi bi-calendar3 me-1"></i>Échéance : ${dateFr(x.date_echeance)}</div>${x.plan_item_title?`<div class="task-meta mt-1"><i class="bi bi-list-check me-1"></i>Plan : ${esc(x.plan_item_title)}</div>`:''}${x.description?`<p class="mb-1 mt-2">${esc(x.description)}</p>`:''}${x.commentaire_stagiaire?`<div class="small mt-2"><strong>Stagiaire :</strong> ${esc(x.commentaire_stagiaire)}</div>`:''}${x.commentaire_encadreur?`<div class="small"><strong>Encadreur :</strong> ${esc(x.commentaire_encadreur)}</div>`:''}</div><div>${actions(x)}</div></div></div>`).join(''):'<div class="task-card text-center text-muted py-5">Aucune tâche.</div>';document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editTask(Number(b.dataset.id)));document.querySelectorAll('.status').forEach(b=>b.onclick=()=>changeStatus(Number(b.dataset.id),b.dataset.action));}
function fillFilters(){const old=$('studentFilter').value;$('studentFilter').innerHTML='<option value="">Tous les stagiaires</option>'+data.students.map(s=>`<option value="${s.id}">${esc(s.name)} · ${esc(s.stagia_code||'')}</option>`).join('');$('studentFilter').value=old;$('addBtn').classList.toggle('d-none',!data.can_manage);}
async function load(){const q=new URLSearchParams();if($('search').value.trim())q.set('search',$('search').value.trim());if($('statusFilter').value)q.set('status',$('statusFilter').value);if($('studentFilter').value)q.set('student_id',$('studentFilter').value);try{const r=await STAGIA.request(BASE+'/actions/espace-hopital/task-list.php?'+q);data=r.data||data;const s=data.stats||{};$('kTotal').textContent=s.total||0;$('kTodo').textContent=s.a_faire||0;$('kDoing').textContent=s.en_cours||0;$('kDone').textContent=s.terminees||0;$('kValid').textContent=s.validees||0;fillFilters();progress();render();}catch(e){STAGIA.toast(e.message,'danger');}}
function updateDependent(){const aid=Number($('assignment').value)||0;$('rotation').innerHTML='<option value="">Tâche générale du stage</option>'+data.rotations.filter(r=>Number(r.assignment_id)===aid).map(r=>`<option value="${r.id}">${esc(r.unit_name||'Rotation')} · #${Number(r.sequence_no)||''} · ${dateFr(r.date_debut)} → ${dateFr(r.date_fin)}</option>`).join('');$('planItem').innerHTML='<option value="">Aucun élément du plan</option>'+data.plan_items.filter(i=>Number(i.assignment_id)===aid).map(i=>`<option value="${i.id}">${esc(i.type_item)} · ${esc(i.titre)}</option>`).join('');}
function openCreate(){$('taskForm').reset();$('taskId').value='';$('taskModalTitle').textContent='Nouvelle tâche';$('assignment').disabled=false;$('assignment').innerHTML='<option value="">Sélectionner...</option>'+data.assignments.map(a=>`<option value="${a.assignment_id}">${esc(a.student_name)} · ${esc(a.stagia_code||'')}</option>`).join('');updateDependent();modal.show();}
function editTask(id){const x=data.items.find(v=>Number(v.id)===id);if(!x)return;$('taskForm').reset();$('taskId').value=x.id;$('taskModalTitle').textContent='Modifier la tâche';$('assignment').innerHTML=`<option value="${x.assignment_id}">${esc(x.student_name)} · ${esc(x.stagia_code||'')}</option>`;$('assignment').value=x.assignment_id;$('assignment').disabled=true;updateDependent();$('rotation').value=x.rotation_id||'';$('planItem').value=x.training_plan_item_id||'';$('title').value=x.titre||'';$('description').value=x.description||'';$('priority').value=x.priorite||'NORMALE';$('due').value=x.date_echeance||'';modal.show();}
$('taskForm').onsubmit=async e=>{e.preventDefault();STAGIA.loading($('saveBtn'),true);try{const fd=new FormData(e.currentTarget);if($('assignment').disabled)fd.set('assignment_id',data.items.find(v=>Number(v.id)===Number($('taskId').value))?.assignment_id||'');const url=$('taskId').value?BASE+'/actions/espace-hopital/task-update.php':BASE+'/actions/espace-hopital/task-store.php';const r=await STAGIA.post(url,fd);STAGIA.toast(r.message);modal.hide();await load();}catch(e){STAGIA.toast(e.message,'danger');}finally{STAGIA.loading($('saveBtn'),false);}};
async function changeStatus(id,action){let comment='';if(action==='VALIDATE'){comment=prompt('Commentaire de validation (facultatif) :')||'';if(!STAGIA.confirm('Valider définitivement cette tâche ?'))return;}else if(action==='REVIEW'){comment=prompt('Correction demandée au stagiaire :')||'';if(!comment.trim())return;}else{comment=prompt("Motif d'annulation :")||'';if(!comment.trim())return;}const fd=new FormData();fd.append('csrf',CSRF);fd.append('id',id);fd.append('action',action);fd.append('commentaire',comment);try{const r=await STAGIA.post(BASE+'/actions/espace-hopital/task-status.php',fd);STAGIA.toast(r.message);await load();}catch(e){STAGIA.toast(e.message,'danger');}}
$('assignment').onchange=updateDependent;$('addBtn').onclick=openCreate;$('refreshBtn').onclick=load;$('statusFilter').onchange=load;$('studentFilter').onchange=load;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(load,300);};load();
});
</script>
<?php require_once __DIR__.'/../../includes/app-footer.php'; ?>
