<?php
require_once __DIR__.'/../../../config/config.php';
require_once __DIR__.'/../../../config/database.php';
require_once __DIR__.'/../../../includes/auth.php';
require_once __DIR__.'/../../../includes/permissions.php';
requireRole(['SUPER_ADMIN']);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$pageTitle='Paramètres';$activePage='admin-parametres';
function e($v){return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
function row($t,$d,$h){echo '<div class="setting-row"><div class="setting-label"><strong>'.$t.'</strong><small>'.$d.'</small></div>'.$h.'</div>';}
function inputx($k,$id,$type='text',$attrs=''){return '<input type="'.$type.'" class="form-control" name="settings['.$k.']" id="'.$id.'" '.$attrs.'>';}
function swx($k,$id){return '<div class="form-check form-switch"><input type="hidden" name="settings['.$k.']" value="0"><input class="form-check-input" type="checkbox" name="settings['.$k.']" value="1" id="'.$id.'"></div>';}
require_once __DIR__.'/../../../includes/app-header.php';
?>
<style>
.settings-layout{display:grid;grid-template-columns:250px minmax(0,1fr);gap:20px;align-items:start}.settings-nav,.settings-card{background:#fff;border:1px solid #e7ebf0;border-radius:16px}.settings-nav{padding:10px;position:sticky;top:90px}.settings-nav button{width:100%;border:0;background:transparent;border-radius:10px;padding:11px 12px;text-align:left;color:#475569;font-size:14px}.settings-nav button.active,.settings-nav button:hover{background:#fff3e9;color:#ea580c}.settings-card{margin-bottom:18px;overflow:hidden}.settings-card-head{padding:17px 20px;border-bottom:1px solid #eef2f7}.settings-card-head h5{margin:0;font-size:16px}.settings-card-head p,.setting-label small{margin:4px 0 0;color:#64748b;font-size:13px}.settings-card-body{padding:20px}.setting-row{display:grid;grid-template-columns:minmax(220px,1fr) minmax(280px,1fr);gap:24px;padding:17px 0;border-bottom:1px solid #f1f5f9;align-items:center}.setting-row:first-child{padding-top:0}.setting-row:last-child{border-bottom:0;padding-bottom:0}.setting-label strong{display:block;font-size:14px}.setting-label small{display:block}.settings-savebar{position:sticky;bottom:15px;background:#111827;color:#fff;border-radius:14px;padding:12px 16px;display:flex;align-items:center;justify-content:space-between;gap:15px;box-shadow:0 10px 30px rgba(15,23,42,.18);z-index:20}.form-switch .form-check-input{width:2.7em;height:1.35em}.fee-table td,.fee-table th{font-size:13px;vertical-align:middle}@media(max-width:900px){.settings-layout{grid-template-columns:1fr}.settings-nav{position:static}.setting-row{grid-template-columns:1fr}}
</style>
<main class="dashboard-content">
<div class="stagia-page-head"><div><h1>Paramètres</h1><p>Configuration globale de STAGIA-RDC.</p></div></div>
<div class="alert alert-light border"><i class="bi bi-info-circle text-primary me-1"></i>Ces valeurs s’appliquent à l’ensemble de la plateforme.</div>
<form id="settingsForm"><input type="hidden" name="csrf" value="<?=e($_SESSION['csrf'])?>"><div class="settings-layout">
<aside class="settings-nav">
<?php foreach(['PLATEFORME'=>'bi-window|Plateforme','SECURITE'=>'bi-shield-lock|Sécurité','ADHESION'=>'bi-building-add|Adhésion','PAIEMENTS'=>'bi-credit-card|Paiements','NOTIFICATIONS'=>'bi-envelope|Notifications','MAINTENANCE'=>'bi-tools|Maintenance'] as $k=>$v):[$i,$l]=explode('|',$v);?>
<button type="button" class="<?=$k==='PLATEFORME'?'active':''?>" data-target="<?=$k?>"><i class="bi <?=$i?> me-2"></i><?=$l?></button>
<?php endforeach; ?>
</aside><section>
<div class="settings-card" data-category="PLATEFORME"><div class="settings-card-head"><h5>Plateforme</h5><p>Identité et informations générales.</p></div><div class="settings-card-body">
<?php row('Nom de la plateforme','Nom principal affiché.',inputx('platform.name','platform_name','text','maxlength="255"'));row('Sous-titre','Libellé institutionnel.',inputx('platform.subtitle','platform_subtitle','text','maxlength="255"'));row('E-mail de support','Adresse de contact centrale.',inputx('platform.support_email','platform_support_email','email'));row('Téléphone de support','Numéro de contact central.',inputx('platform.support_phone','platform_support_phone'));row('Fuseau horaire','Fuseau par défaut.','<select class="form-select" name="settings[platform.timezone]" id="platform_timezone"><option>Africa/Kinshasa</option><option>Africa/Lubumbashi</option><option>UTC</option></select>');?>
</div></div>
<div class="settings-card" data-category="SECURITE"><div class="settings-card-head"><h5>Sécurité des comptes</h5><p>Sessions, invitations et verrouillage.</p></div><div class="settings-card-body">
<?php row('Durée de session','5 à 1440 minutes.','<div class="input-group">'.inputx('security.session_timeout_minutes','security_session_timeout_minutes','number','min="5" max="1440"').'<span class="input-group-text">minutes</span></div>');row('Validité d’une invitation','Durée du lien d’activation.','<div class="input-group">'.inputx('security.activation_expiry_hours','security_activation_expiry_hours','number','min="1" max="720"').'<span class="input-group-text">heures</span></div>');row('Tentatives de connexion','Nombre maximal avant blocage.',inputx('security.max_login_attempts','security_max_login_attempts','number','min="1" max="20"'));row('Durée du verrouillage','Blocage temporaire.','<div class="input-group">'.inputx('security.lockout_minutes','security_lockout_minutes','number','min="1" max="1440"').'<span class="input-group-text">minutes</span></div>');?>
</div></div>
<div class="settings-card" data-category="ADHESION"><div class="settings-card-head"><h5>Adhésion</h5><p>Demande publique d’adhésion.</p></div><div class="settings-card-body"><?php row('Adhésions ouvertes','Autoriser les demandes d’établissement.',swx('adhesion.enabled','adhesion_enabled'));?></div></div>
<div class="settings-card" data-category="PAIEMENTS"><div class="settings-card-head"><h5>Paiement création compte étudiant</h5><p>Activation annuelle étudiant et MaishaPay.</p></div><div class="settings-card-body">
<div class="alert alert-info small mb-4"><i class="bi bi-shield-lock me-1"></i>Les identifiants MaishaPay sont configurés uniquement dans les variables d’environnement du serveur.</div>
<?php row('Paiement obligatoire','Exiger Mobile Money avant activation / renouvellement.',swx('student_activation.payment_enabled','student_activation_payment_enabled'));row('Frais annuels','Montant demandé à l’étudiant.',inputx('student_activation.amount','student_activation_amount','number','min="0" step="0.01"'));row('Devise','USD, CDF ou EUR.',inputx('student_activation.currency','student_activation_currency','text','maxlength="10"'));?>
</div></div>
<div class="settings-card" data-category="PAIEMENTS"><div class="settings-card-head"><h5>Frais STAGIA hôpital / niveau</h5><p>Montants appliqués selon l’hôpital d’accueil et le niveau académique.</p></div><div class="settings-card-body">
<div class="row g-2 mb-3"><div class="col-lg-4"><select id="feeHost" class="form-select"><option value="">Hôpital...</option></select></div><div class="col-lg-3"><select id="feeLevel" class="form-select"><option value="">Niveau...</option></select></div><div class="col-lg-2"><input id="feeAmount" type="number" min="0" step="0.01" class="form-control" placeholder="Montant"></div><div class="col-lg-2"><select id="feeCurrency" class="form-select"><option>USD</option><option>CDF</option><option>EUR</option></select></div><div class="col-lg-1 d-grid"><button type="button" id="feeSave" class="btn btn-primary-stagia"><i class="bi bi-check-lg"></i></button></div></div>
<div class="table-responsive"><table class="table fee-table align-middle"><thead><tr><th>Hôpital</th><th>Niveau</th><th>Montant</th><th>Statut</th><th class="text-end">Action</th></tr></thead><tbody id="feeRows"><tr><td colspan="5" class="text-center text-muted py-4">Chargement...</td></tr></tbody></table></div>
</div></div>
<div class="settings-card" data-category="NOTIFICATIONS"><div class="settings-card-head"><h5>Notifications</h5><p>Canaux système.</p></div><div class="settings-card-body"><?php row('Notifications e-mail','Invitations et notifications SMTP.',swx('notifications.email_enabled','notifications_email_enabled'));?></div></div>
<div class="settings-card" data-category="MAINTENANCE"><div class="settings-card-head"><h5>Maintenance</h5><p>Verrouillage contrôlé.</p></div><div class="settings-card-body"><?php row('Mode maintenance','Bloquer temporairement la plateforme.',swx('maintenance.enabled','maintenance_enabled'));row('Message de maintenance','Texte affiché aux utilisateurs.','<textarea class="form-control" rows="4" maxlength="1000" name="settings[maintenance.message]" id="maintenance_message"></textarea>');?></div></div>
<div class="settings-savebar"><span><i class="bi bi-shield-check me-2"></i>Paramètres globaux STAGIA</span><button class="btn btn-primary-stagia" id="saveBtn"><i class="bi bi-check-lg me-1"></i>Enregistrer</button></div>
</section></div></form></main>
<script>
document.addEventListener('DOMContentLoaded',()=>{const BASE='<?=BASE_URL?>',$=id=>document.getElementById(id),esc=STAGIA.escape,csrf='<?=e($_SESSION['csrf'])?>';let fees={hospitals:[],levels:[],items:[]};
const map={'platform.name':'platform_name','platform.subtitle':'platform_subtitle','platform.support_email':'platform_support_email','platform.support_phone':'platform_support_phone','platform.timezone':'platform_timezone','security.session_timeout_minutes':'security_session_timeout_minutes','security.activation_expiry_hours':'security_activation_expiry_hours','security.max_login_attempts':'security_max_login_attempts','security.lockout_minutes':'security_lockout_minutes','adhesion.enabled':'adhesion_enabled','student_activation.payment_enabled':'student_activation_payment_enabled','student_activation.amount':'student_activation_amount','student_activation.currency':'student_activation_currency','notifications.email_enabled':'notifications_email_enabled','maintenance.enabled':'maintenance_enabled','maintenance.message':'maintenance_message'};
async function loadSettings(){try{const r=await STAGIA.request(BASE+'/actions/admin/parametres/list.php');(r.data.items||[]).forEach(s=>{const el=$(map[s.setting_key]);if(!el)return;if(el.type==='checkbox')el.checked=Number(s.setting_value)===1;else if(!s.configured)el.value=s.setting_value??'';else el.placeholder='Valeur configurée. Saisissez une nouvelle valeur pour la remplacer.';});}catch(e){STAGIA.toast(e.message,'danger');}}
function feeSelects(){ $('feeHost').innerHTML='<option value="">Hôpital...</option>'+fees.hospitals.map(x=>`<option value="${x.id}">${esc(x.nom)}</option>`).join('');$('feeLevel').innerHTML='<option value="">Niveau...</option>'+fees.levels.map(x=>`<option value="${x.id}">${esc(x.label)}</option>`).join('');}
function renderFees(){const rows=fees.items||[];$('feeRows').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.host_name)}</td><td><strong>${esc(x.niveau_code)}</strong><small class="d-block text-muted">${esc(x.niveau_libelle)}</small></td><td><strong>${esc(x.amount)} ${esc(x.currency)}</strong></td><td><span class="badge bg-${Number(x.actif)?'success':'secondary'}-subtle text-${Number(x.actif)?'success':'secondary'}">${Number(x.actif)?'Actif':'Inactif'}</span></td><td class="text-end"><div class="btn-group btn-group-sm"><button type="button" class="btn btn-outline-primary" data-edit="${x.id}"><i class="bi bi-pencil"></i></button><button type="button" class="btn btn-outline-${Number(x.actif)?'danger':'success'}" data-status="${x.id}" data-actif="${Number(x.actif)?0:1}"><i class="bi bi-${Number(x.actif)?'pause':'play'}"></i></button></div></td></tr>`).join(''):'<tr><td colspan="5" class="text-center text-muted py-4">Aucun frais configuré.</td></tr>';}
async function loadFees(){try{const r=await STAGIA.request(BASE+'/actions/admin/stagia-fees-list.php');fees=r.data||fees;feeSelects();renderFees();}catch(e){$('feeRows').innerHTML=`<tr><td colspan="5" class="text-danger text-center py-4">${esc(e.message)}</td></tr>`;}}
$('settingsForm').onsubmit=async e=>{e.preventDefault();STAGIA.loading($('saveBtn'),true);try{const r=await STAGIA.post(BASE+'/actions/admin/parametres/update.php',new FormData(e.currentTarget));STAGIA.toast(r.message);}catch(e){STAGIA.toast(e.message,'danger');}finally{STAGIA.loading($('saveBtn'),false);}};
$('feeSave').onclick=async()=>{const fd=new FormData();fd.append('csrf',csrf);fd.append('host_etablissement_id',$('feeHost').value);fd.append('academic_level_id',$('feeLevel').value);fd.append('amount',$('feeAmount').value);fd.append('currency',$('feeCurrency').value);STAGIA.loading($('feeSave'),true);try{const r=await STAGIA.post(BASE+'/actions/admin/stagia-fees-store.php',fd);STAGIA.toast(r.message);$('feeAmount').value='';await loadFees();}catch(e){STAGIA.toast(e.message,'danger');}finally{STAGIA.loading($('feeSave'),false);}};
$('feeRows').onclick=async e=>{const b=e.target.closest('[data-edit],[data-status]');if(!b)return;if(b.dataset.edit){const x=fees.items.find(v=>String(v.id)===b.dataset.edit);if(!x)return;$('feeHost').value=x.host_etablissement_id;$('feeLevel').value=x.academic_level_id;$('feeAmount').value=x.amount;$('feeCurrency').value=x.currency;return;}const fd=new FormData();fd.append('csrf',csrf);fd.append('id',b.dataset.status);fd.append('actif',b.dataset.actif);try{const r=await STAGIA.post(BASE+'/actions/admin/stagia-fees-status.php',fd);STAGIA.toast(r.message);await loadFees();}catch(e){STAGIA.toast(e.message,'danger');}};
document.querySelectorAll('.settings-nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.settings-nav button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector(`[data-category="${btn.dataset.target}"]`)?.scrollIntoView({behavior:'smooth',block:'start'});});
loadSettings();loadFees();});
</script>
<?php require_once __DIR__.'/../../../includes/app-footer.php'; ?>
