<?php
/**
 * Endpoint AJAX de consultation des plans de formation et de leurs éléments pédagogiques.
 * Il renvoie aussi les référentiels et listes de choix autorisés dans le contexte de l'établissement.
 */
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/auth.php';
require_once __DIR__.'/../../includes/ajax.php';
require_once __DIR__.'/../../includes/permissions.php';
require_once __DIR__.'/../../includes/stage-training.php';

try{
    /* Les types de campagnes autorisés sont calculés selon le droit de consultation du rôle connecté. */
    requireTrainingPlanAccess($pdo,'view');$eid=trainingEtablissementId($pdo);$types=trainingAllowedCampaignTypes($pdo,'view');
    $ph=implode(',',array_fill(0,count($types),'?'));
    $params=array_merge([$eid],$types);
    $s=$pdo->prepare("SELECT p.id,p.uuid,p.campaign_id,p.referential_id,p.titre,p.description,p.statut,p.published_at,p.created_at,p.updated_at,c.code campaign_code,c.titre campaign_title,c.type_campagne,c.stage_type_id,c.date_debut campaign_start,c.date_fin campaign_end,c.statut campaign_status,st.libelle stage_type_libelle,r.code referential_code,r.libelle referential_label,r.version referential_version,(SELECT COUNT(*) FROM stage_training_plan_items i WHERE i.plan_id=p.id AND i.actif=1) items_count FROM stage_training_plans p JOIN stage_campaigns c ON c.id=p.campaign_id JOIN stage_types st ON st.id=c.stage_type_id LEFT JOIN stage_referentials r ON r.id=p.referential_id WHERE c.owner_etablissement_id=? AND c.type_campagne IN($ph) ORDER BY p.updated_at DESC,p.id DESC");
    $s->execute($params);$items=$s->fetchAll(PDO::FETCH_ASSOC);$by=[];foreach($items as &$x){$x['id']=(int)$x['id'];$x['campaign_id']=(int)$x['campaign_id'];$x['referential_id']=$x['referential_id']!==null?(int)$x['referential_id']:null;$x['stage_type_id']=(int)$x['stage_type_id'];$x['items_count']=(int)$x['items_count'];$x['items']=[];$by[$x['id']]=&$x;}unset($x);
    if($by){$ids=array_keys($by);$iph=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT i.id,i.plan_id,i.referential_objective_id,i.host_unit_id,i.responsible_user_id,i.ordre,i.type_item,i.titre,i.description,i.date_debut_prevue,i.date_fin_prevue,i.obligatoire,i.actif,o.code objective_code,o.libelle objective_label,hu.code host_unit_code,hu.nom host_unit_name,TRIM(CONCAT_WS(' ',u.prenom,u.nom,u.postnom)) responsible_name FROM stage_training_plan_items i LEFT JOIN stage_referential_objectives o ON o.id=i.referential_objective_id LEFT JOIN host_units hu ON hu.id=i.host_unit_id LEFT JOIN users u ON u.id=i.responsible_user_id WHERE i.plan_id IN($iph) ORDER BY i.plan_id,i.ordre,i.id");$q->execute($ids);foreach($q->fetchAll(PDO::FETCH_ASSOC) as $it){foreach(['id','plan_id','ordre','obligatoire','actif'] as $k)$it[$k]=(int)$it[$k];foreach(['referential_objective_id','host_unit_id','responsible_user_id'] as $k)$it[$k]=$it[$k]!==null?(int)$it[$k]:null;$by[$it['plan_id']]['items'][]=$it;}}
    $c=$pdo->prepare("SELECT c.id,c.code,c.titre,c.stage_type_id,c.type_campagne,c.date_debut,c.date_fin,c.statut,st.libelle stage_type_libelle FROM stage_campaigns c JOIN stage_types st ON st.id=c.stage_type_id WHERE c.owner_etablissement_id=? AND c.type_campagne IN($ph) AND c.statut NOT IN('ANNULEE','TERMINEE') ORDER BY c.date_debut DESC,c.id DESC");$c->execute($params);$campaigns=$c->fetchAll(PDO::FETCH_ASSOC);foreach($campaigns as &$x){$x['id']=(int)$x['id'];$x['stage_type_id']=(int)$x['stage_type_id'];}unset($x);
    $r=$pdo->prepare("SELECT id,code,libelle,version,stage_type_id FROM stage_referentials WHERE etablissement_id=? AND statut='ACTIF' ORDER BY libelle,version");$r->execute([$eid]);$refs=$r->fetchAll(PDO::FETCH_ASSOC);foreach($refs as &$x){$x['id']=(int)$x['id'];$x['stage_type_id']=(int)$x['stage_type_id'];}unset($x);
    $o=$pdo->prepare("SELECT o.id,o.referential_id,o.code,o.libelle,o.description,o.ordre,o.obligatoire FROM stage_referential_objectives o JOIN stage_referentials r ON r.id=o.referential_id WHERE r.etablissement_id=? AND r.statut='ACTIF' ORDER BY o.referential_id,o.ordre,o.id");$o->execute([$eid]);$objectives=$o->fetchAll(PDO::FETCH_ASSOC);foreach($objectives as &$x){$x['id']=(int)$x['id'];$x['referential_id']=(int)$x['referential_id'];$x['ordre']=(int)$x['ordre'];$x['obligatoire']=(int)$x['obligatoire'];}unset($x);
    $units=[];if(contextHostEnabled()){$u=$pdo->prepare("SELECT id,code,nom FROM host_units WHERE host_etablissement_id=? AND actif=1 ORDER BY nom");$u->execute([$eid]);$units=$u->fetchAll(PDO::FETCH_ASSOC);foreach($units as &$x)$x['id']=(int)$x['id'];unset($x);}
    $u=$pdo->prepare("SELECT u.id,TRIM(CONCAT_WS(' ',u.prenom,u.nom,u.postnom)) nom_complet FROM users u WHERE u.statut_compte='ACTIF' AND EXISTS(SELECT 1 FROM etablissement_users eu WHERE eu.user_id=u.id AND eu.etablissement_id=?) ORDER BY u.nom,u.prenom,u.id");$u->execute([$eid]);$users=$u->fetchAll(PDO::FETCH_ASSOC);foreach($users as &$x)$x['id']=(int)$x['id'];unset($x);
    $k=['total'=>count($items),'draft'=>0,'published'=>0,'archived'=>0];foreach($items as $x){if($x['statut']==='BROUILLON')$k['draft']++;elseif($x['statut']==='PUBLIE')$k['published']++;elseif($x['statut']==='ARCHIVE')$k['archived']++;}
    jsonResponse(true,'',['items'=>$items,'campaigns'=>$campaigns,'referentials'=>$refs,'objectives'=>$objectives,'units'=>$units,'users'=>$users,'kpi'=>$k,'permissions'=>['create'=>!empty(trainingAllowedCampaignTypes($pdo,'create')),'update'=>!empty(trainingAllowedCampaignTypes($pdo,'update')),'publish'=>!empty(trainingAllowedCampaignTypes($pdo,'publish'))]]);
}catch(Throwable $e){jsonResponse(false,$e->getMessage(),[],403);}
