<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/permissions.php';require_once __DIR__.'/../../includes/communication-native.php';header('Content-Type: application/json; charset=utf-8');
function ok(string $message,array $data=[]):never{echo json_encode(['success'=>true,'message'=>$message,'data'=>$data],JSON_UNESCAPED_UNICODE);exit;}function fail(string $message,int $code=422):never{http_response_code($code);echo json_encode(['success'=>false,'message'=>$message],JSON_UNESCAPED_UNICODE);exit;}
if(!communicationUtilisateurAutorise($pdo))fail('Accès refusé.',403);if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??'')))fail('Session expirée. Rechargez la page.',419);
$a=(string)($_POST['action']??'');$u=(int)$_SESSION['user_id'];$org=communicationEtablissementId($pdo);$role=(string)($_SESSION['role_code']??'');
if($a==='publication'&&communicationEstEtudiant())fail('Votre profil ne peut pas publier une communication officielle.',403);
if($a==='message'&&trim((string)($_POST['contenu']??''))===''&&(int)($_FILES['piece_jointe']['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)fail('Écrivez un message ou ajoutez une pièce jointe.');
try{
    if($a==='brouillon_enregistrer'){$conversation=(int)($_POST['conversation_id']??0);$contenu=trim((string)($_POST['contenu']??''));if(!communicationVerifierParticipant($pdo,$conversation,$u))fail('Conversation inaccessible.',403);if($contenu===''){$pdo->prepare('DELETE FROM brouillons_messages WHERE utilisateur_id=? AND conversation_id=?')->execute([$u,$conversation]);ok('Brouillon supprimé.');}$pdo->prepare('INSERT INTO brouillons_messages(utilisateur_id,conversation_id,contenu) VALUES(?,?,?) ON DUPLICATE KEY UPDATE contenu=VALUES(contenu),modifie_le=UTC_TIMESTAMP(6)')->execute([$u,$conversation,$contenu]);ok('Brouillon enregistré.');}
    if($a==='brouillon_supprimer'){$pdo->prepare('DELETE FROM brouillons_messages WHERE utilisateur_id=? AND conversation_id=?')->execute([$u,(int)($_POST['conversation_id']??0)]);ok('Brouillon supprimé.');}
    $destinataires=[];if(in_array($a,['conversation','publication','evenement'],true)){$cible=(string)($_POST['cible']??('personne:'.(int)($_POST['destinataire_id']??0)));$destinataires=communicationResoudreCible($pdo,$u,(int)$org,$role,$cible);if(!$destinataires)fail('Cette sélection ne contient aucun membre autorisé dans votre périmètre institutionnel.',403);}
    if($a==='conversation'){$objet=trim((string)($_POST['objet']??''));if($objet===''||mb_strlen($objet)>255)fail('Vérifiez l’objet et les destinataires.');$pdo->beginTransaction();$type=count($destinataires)>1?'groupe':'privee';$pdo->prepare('INSERT INTO conversations(identifiant_public,type_conversation,objet,cree_par_utilisateur_id) VALUES(?,?,?,?)')->execute([communicationUlid(),$type,$objet,$u]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('INSERT INTO participants_conversations(conversation_id,utilisateur_id,organisation_representation_id) VALUES(?,?,?)');$q->execute([$id,$u,$org]);foreach($destinataires as $dest){$q->execute([$id,$dest,null]);communicationNotifier($pdo,$dest,$org,'nouvelle_conversation','Nouvelle conversation',$objet,BASE_URL.'/views/communication/index.php?conversation='.$id);}$pdo->commit();ok(count($destinataires)>1?'Conversation de groupe créée.':'Conversation créée.',['id'=>$id,'destinataires'=>count($destinataires)]);}
    if($a==='message'){$id=(int)($_POST['conversation_id']??0);$texte=trim((string)($_POST['contenu']??''));$fichier=$_FILES['piece_jointe']??null;if(!communicationVerifierParticipant($pdo,$id,$u)||($texte===''&&!$fichier)||mb_strlen($texte)>10000)fail('Ajoutez un message ou une pièce jointe valide.');$pdo->beginTransaction();$contenu=$texte!==''?$texte:'Pièce jointe';$pdo->prepare('INSERT INTO messages(identifiant_public,conversation_id,auteur_utilisateur_id,organisation_auteur_id,contenu) VALUES(?,?,?,?,?)')->execute([communicationUlid(),$id,$u,$org,$contenu]);$mid=(int)$pdo->lastInsertId();if($fichier){$fid=communicationEnregistrerFichier($pdo,$fichier,$u);if($fid)$pdo->prepare('INSERT INTO pieces_jointes_messages(message_id,fichier_id) VALUES(?,?)')->execute([$mid,$fid]);}$pdo->prepare('UPDATE participants_conversations SET dernier_message_lu_id=? WHERE conversation_id=? AND utilisateur_id=?')->execute([$mid,$id,$u]);$pdo->prepare('DELETE FROM brouillons_messages WHERE utilisateur_id=? AND conversation_id=?')->execute([$u,$id]);$q=$pdo->prepare('SELECT utilisateur_id FROM participants_conversations WHERE conversation_id=? AND utilisateur_id<>? AND quitte_le IS NULL');$q->execute([$id,$u]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $dest)communicationNotifier($pdo,(int)$dest,$org,'nouveau_message','Nouveau message',mb_substr($contenu,0,180),BASE_URL.'/views/communication/index.php?conversation='.$id);$pdo->commit();ok('Message envoyé.');}
    if($a==='publication'){$type=(string)($_POST['type_communication']??'annonce');$objet=trim((string)($_POST['objet']??''));$texte=trim((string)($_POST['contenu']??''));$accuse=!empty($_POST['accuse']);if(!in_array($type,['annonce','circulaire','directive','note_service','convocation','demande_information','alerte'],true)||$objet===''||$texte==='')fail('Complétez les informations de la publication.');$pdo->beginTransaction();$ref='COM-'.gmdate('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));$pdo->prepare("INSERT INTO communications_officielles(identifiant_public,organisation_emettrice_id,type_communication,reference,objet,contenu,accuse_reception_requis,statut,publiee_par_utilisateur_id,publiee_le) VALUES(?,?,?,?,?,?,?,'publiee',?,UTC_TIMESTAMP(6))")->execute([communicationUlid(),$org,$type,$ref,$objet,$texte,(int)$accuse,$u]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare("INSERT INTO destinataires_communications(communication_officielle_id,utilisateur_id,statut_remise,remise_le) VALUES(?,?,'remise',UTC_TIMESTAMP(6))");foreach($destinataires as $dest){$q->execute([$id,$dest]);communicationNotifier($pdo,$dest,$org,'communication_officielle',$objet,mb_substr($texte,0,180),BASE_URL.'/views/communication/index.php#publications');}$pdo->commit();ok('Communication publiée à '.count($destinataires).' destinataire(s).');}
    if($a==='message_lu'){$conversation=(int)($_POST['conversation_id']??0);$message=(int)($_POST['message_id']??0);if(!communicationVerifierParticipant($pdo,$conversation,$u))fail('Conversation inaccessible.',403);$q=$pdo->prepare("SELECT id FROM messages WHERE id=? AND conversation_id=? AND auteur_utilisateur_id<>? AND statut IN ('envoye','modifie')");$q->execute([$message,$conversation,$u]);if(!$q->fetchColumn())fail('Message inaccessible.',403);$pdo->prepare('UPDATE participants_conversations SET dernier_message_lu_id=GREATEST(COALESCE(dernier_message_lu_id,0),?) WHERE conversation_id=? AND utilisateur_id=?')->execute([$message,$conversation,$u]);ok('Lecture enregistrée.');}
    if($a==='publication_ouverte'){$id=(int)($_POST['communication_id']??0);$pdo->prepare('UPDATE destinataires_communications d JOIN communications_officielles c ON c.id=d.communication_officielle_id SET d.lue_le=COALESCE(d.lue_le,UTC_TIMESTAMP(6)),d.accusee_le=CASE WHEN c.accuse_reception_requis=1 THEN COALESCE(d.accusee_le,UTC_TIMESTAMP(6)) ELSE d.accusee_le END WHERE d.utilisateur_id=? AND d.communication_officielle_id=?')->execute([$u,$id]);ok('Ouverture et accusé de réception enregistrés.');}
    if($a==='evenement'){$titre=trim((string)($_POST['titre']??''));$debut=DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',(string)($_POST['debut']??''));$fin=DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',(string)($_POST['fin']??''));if($titre===''||!$debut||!$fin||$fin<$debut)fail('Vérifiez la période et les participants.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO evenements_calendrier(identifiant_public,organisation_id,titre,type_evenement,debut,fin,cree_par_utilisateur_id) VALUES(?,?,?,'reunion',?,?,?)")->execute([communicationUlid(),$org,$titre,$debut->format('Y-m-d H:i:s'),$fin->format('Y-m-d H:i:s'),$u]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('INSERT INTO participants_evenements(evenement_calendrier_id,utilisateur_id,statut_reponse,repondu_le) VALUES(?,?,?,?)');$q->execute([$id,$u,'accepte',gmdate('Y-m-d H:i:s')]);foreach($destinataires as $dest){$q->execute([$id,$dest,'invite',null]);communicationNotifier($pdo,$dest,$org,'invitation_calendrier','Nouvel événement',$titre,BASE_URL.'/views/communication/index.php#calendar');}$pdo->commit();ok('Événement planifié pour '.count($destinataires).' participant(s).');}
    if($a==='reponse'){$rep=(string)($_POST['reponse']??'');if(!in_array($rep,['accepte','refuse','incertain'],true))fail('Réponse invalide.');$pdo->prepare('UPDATE participants_evenements SET statut_reponse=?,repondu_le=UTC_TIMESTAMP(6) WHERE evenement_calendrier_id=? AND utilisateur_id=?')->execute([$rep,(int)($_POST['evenement_id']??0),$u]);ok('Réponse enregistrée.');}
    if($a==='notification_lue'){$pdo->prepare('UPDATE notifications SET lue_le=COALESCE(lue_le,UTC_TIMESTAMP(6)) WHERE utilisateur_id=? AND id=?')->execute([$u,(int)($_POST['notification_id']??0)]);ok('Notification lue.');}
    fail('Action inconnue.');
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log((string)$e);fail($e instanceof RuntimeException?$e->getMessage():'Une erreur technique empêche l’opération.',500);}
