<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/permissions.php';require_once __DIR__.'/../../includes/communication-native.php';header('Content-Type: application/json; charset=utf-8');requireCommunicationRole();
$u=(int)$_SESSION['user_id'];$org=communicationEtablissementId($pdo);$action=(string)($_GET['action']??'index');
function espacesSql():string{return "(e.organisation_proprietaire_id=:org OR EXISTS(SELECT 1 FROM membres_espaces me WHERE me.espace_collaboratif_id=e.id AND me.quitte_le IS NULL AND (me.utilisateur_id=:u OR me.organisation_id=:org2)))";}
try{
 if($action==='sujet'){$id=(int)($_GET['id']??0);$q=$pdo->prepare("SELECT s.id,s.titre,s.contenu,s.statut,s.epingle,s.cree_le,e.nom espace,TRIM(CONCAT_WS(' ',u.prenom,u.nom)) auteur FROM sujets_forums s JOIN espaces_collaboratifs e ON e.id=s.espace_collaboratif_id JOIN users u ON u.id=s.auteur_utilisateur_id WHERE s.id=:id AND ".espacesSql());$q->execute(['id'=>$id,'org'=>$org,'u'=>$u,'org2'=>$org]);$sujet=$q->fetch();if(!$sujet){http_response_code(404);throw new RuntimeException('Sujet inaccessible.');}$q=$pdo->prepare("SELECT r.id,r.contenu,r.cree_le,r.auteur_utilisateur_id,TRIM(CONCAT_WS(' ',u.prenom,u.nom)) auteur FROM reponses_forums r JOIN users u ON u.id=r.auteur_utilisateur_id WHERE r.sujet_forum_id=? AND r.statut IN ('publiee','modifiee') ORDER BY r.id");$q->execute([$id]);echo json_encode(['success'=>true,'data'=>['sujet'=>$sujet,'reponses'=>$q->fetchAll()]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
 $q=$pdo->prepare("SELECT e.id,e.nom,e.description,e.type_espace,e.visibilite,e.statut,e.cree_le,e.cree_par_utilisateur_id,o.nom organisation,(SELECT COUNT(*) FROM membres_espaces m WHERE m.espace_collaboratif_id=e.id AND m.quitte_le IS NULL) membres,(SELECT COUNT(*) FROM sujets_forums s WHERE s.espace_collaboratif_id=e.id AND s.statut<>'archive') sujets FROM espaces_collaboratifs e LEFT JOIN etablissements o ON o.id=e.organisation_proprietaire_id WHERE ".espacesSql()." ORDER BY e.statut='actif' DESC,e.cree_le DESC");$q->execute(['org'=>$org,'u'=>$u,'org2'=>$org]);$espaces=$q->fetchAll();
 $q=$pdo->prepare("SELECT s.id,s.titre,s.contenu,s.statut,s.epingle,s.cree_le,s.auteur_utilisateur_id,e.nom espace,TRIM(CONCAT_WS(' ',x.prenom,x.nom)) auteur,(SELECT COUNT(*) FROM reponses_forums r WHERE r.sujet_forum_id=s.id AND r.statut IN ('publiee','modifiee')) reponses FROM sujets_forums s JOIN espaces_collaboratifs e ON e.id=s.espace_collaboratif_id JOIN users x ON x.id=s.auteur_utilisateur_id WHERE s.statut<>'archive' AND ".espacesSql()." ORDER BY s.epingle DESC,s.cree_le DESC LIMIT 100");$q->execute(['org'=>$org,'u'=>$u,'org2'=>$org]);$sujets=$q->fetchAll();
 $q=$pdo->prepare("SELECT ev.id,ev.titre,ev.debut,ev.fin,ev.cree_par_utilisateur_id,rv.id reunion_id,rv.fournisseur,rv.lien_reunion,rv.code_acces,rv.statut FROM reunions_visioconference rv JOIN evenements_calendrier ev ON ev.id=rv.evenement_calendrier_id JOIN participants_evenements p ON p.evenement_calendrier_id=ev.id WHERE p.utilisateur_id=? AND ev.fin>=UTC_TIMESTAMP()-INTERVAL 7 DAY AND ev.statut<>'annule' ORDER BY ev.debut");$q->execute([$u]);$visios=$q->fetchAll();
 $q=$pdo->prepare("SELECT c.id,c.objet,'conversation' type,c.statut,c.cree_le FROM conversations c JOIN participants_conversations p ON p.conversation_id=c.id WHERE p.utilisateur_id=? AND c.statut='archivee' UNION ALL SELECT co.id,co.objet,'communication',co.statut,co.cree_le FROM communications_officielles co LEFT JOIN destinataires_communications dc ON dc.communication_officielle_id=co.id AND dc.utilisateur_id=? WHERE co.statut='archivee' AND (co.publiee_par_utilisateur_id=? OR dc.utilisateur_id=?) UNION ALL SELECT e.id,e.nom,'espace',e.statut,e.cree_le FROM espaces_collaboratifs e JOIN membres_espaces me ON me.espace_collaboratif_id=e.id WHERE e.statut='archive' AND me.utilisateur_id=? AND me.quitte_le IS NULL UNION ALL SELECT s.id,s.titre,'sujet_forum',s.statut,s.cree_le FROM sujets_forums s JOIN espaces_collaboratifs e ON e.id=s.espace_collaboratif_id WHERE s.statut='archive' AND (e.organisation_proprietaire_id=? OR EXISTS(SELECT 1 FROM membres_espaces m WHERE m.espace_collaboratif_id=e.id AND m.utilisateur_id=? AND m.quitte_le IS NULL)) UNION ALL SELECT n.id,n.titre,'notification','archivee',n.cree_le FROM notifications n WHERE n.utilisateur_id=? AND n.archivee_le IS NOT NULL ORDER BY cree_le DESC");$q->execute([$u,$u,$u,$u,$u,$org,$u,$u]);$archives=$q->fetchAll();
 $q=$pdo->prepare("SELECT l.canal,l.statut,COUNT(*) total FROM livraisons_notifications l JOIN notifications n ON n.id=l.notification_id WHERE n.utilisateur_id=? GROUP BY l.canal,l.statut");$q->execute([$u]);$livraisons=$q->fetchAll();
 $q=$pdo->prepare("SELECT canal,active FROM preferences_notifications WHERE utilisateur_id=? AND type_evenement='*'");$q->execute([$u]);$preferences=array_column($q->fetchAll(),'active','canal');
 $sqlCorbeille="SELECT id,type_ressource,ressource_id,libelle,supprime_le FROM corbeille_communications WHERE restaure_le IS NULL".(communicationEstSuperAdministrateur()?'':' AND supprime_par_utilisateur_id=?').' ORDER BY supprime_le DESC LIMIT 200';$q=$pdo->prepare($sqlCorbeille);$q->execute(communicationEstSuperAdministrateur()?[]:[$u]);$corbeille=$q->fetchAll();$configurations=[];if(communicationEstSuperAdministrateur()){$q=$pdo->prepare('SELECT canal,actif,fournisseur,hote,port,nom_utilisateur,adresse_expediteur,nom_expediteur,parametres,secret_chiffre IS NOT NULL secret_defini,modifie_le FROM configurations_canaux_communication WHERE organisation_id <=> ? ORDER BY canal');$q->execute([$org]);$configurations=$q->fetchAll();}
 echo json_encode(['success'=>true,'data'=>['espaces'=>$espaces,'sujets'=>$sujets,'visios'=>$visios,'archives'=>$archives,'corbeille'=>$corbeille,'configurations'=>$configurations,'peut_configurer'=>communicationEstSuperAdministrateur(),'livraisons'=>$livraisons,'preferences'=>$preferences]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){error_log((string)$e);if(http_response_code()<400)http_response_code(500);echo json_encode(['success'=>false,'message'=>$e instanceof RuntimeException?$e->getMessage():'Chargement de la collaboration impossible.'],JSON_UNESCAPED_UNICODE);}
