<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/permissions.php';require_once __DIR__.'/../../includes/communication-native.php';header('Content-Type: application/json; charset=utf-8');requireCommunicationRole();
function success(string $m,array $d=[]):never{echo json_encode(['success'=>true,'message'=>$m,'data'=>$d],JSON_UNESCAPED_UNICODE);exit;}function reject(string $m,int $c=422):never{http_response_code($c);echo json_encode(['success'=>false,'message'=>$m],JSON_UNESCAPED_UNICODE);exit;}
if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??'')))reject('Session expirée.',419);$a=(string)($_POST['action']??'');$u=(int)$_SESSION['user_id'];$org=communicationEtablissementId($pdo);$role=communicationEstEtudiant()?'etudiant':(string)($_SESSION['role_code']??'');
function membreEspace(PDO $pdo,int $espace,int $u,?int $org):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM espaces_collaboratifs e WHERE e.id=? AND (e.organisation_proprietaire_id=? OR EXISTS(SELECT 1 FROM membres_espaces m WHERE m.espace_collaboratif_id=e.id AND m.quitte_le IS NULL AND (m.utilisateur_id=? OR m.organisation_id=?)))');$q->execute([$espace,$org,$u,$org]);return(int)$q->fetchColumn()>0;}
try{
 if($a==='espace'){if($role==='etudiant')reject('La création d’un espace est réservée aux responsables.',403);$nom=trim((string)($_POST['nom']??''));$description=trim((string)($_POST['description']??''));$type=(string)($_POST['type_espace']??'projet');$cible=(string)($_POST['cible']??'');$dest=communicationResoudreCible($pdo,$u,$org,$role,$cible);if($nom===''||!in_array($type,['institution','campagne','stage','projet','forum','autre'],true))reject('Espace invalide.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO espaces_collaboratifs(identifiant_public,organisation_proprietaire_id,type_espace,nom,description,visibilite,statut,cree_par_utilisateur_id) VALUES(?,?,?,?,?,'prive','actif',?)")->execute([communicationUlid(),$org,$type,$nom,$description,$u]);$id=(int)$pdo->lastInsertId();$q=$pdo->prepare('INSERT INTO membres_espaces(espace_collaboratif_id,utilisateur_id,role_membre) VALUES(?,?,?)');$q->execute([$id,$u,'proprietaire']);foreach($dest as $d){$q->execute([$id,$d,'contributeur']);communicationNotifier($pdo,$d,$org,'espace_collaboratif','Invitation à un espace',$nom,BASE_URL.'/views/communication/index.php#spaces');}$pdo->commit();success('Espace collaboratif créé.',['id'=>$id]);}
 if($a==='sujet'){$espace=(int)($_POST['espace_id']??0);if(!membreEspace($pdo,$espace,$u,$org))reject('Espace inaccessible.',403);$titre=trim((string)($_POST['titre']??''));$contenu=trim((string)($_POST['contenu']??''));if($titre===''||$contenu==='')reject('Complétez le sujet.');$pdo->prepare("INSERT INTO sujets_forums(identifiant_public,espace_collaboratif_id,auteur_utilisateur_id,titre,contenu) VALUES(?,?,?,?,?)")->execute([communicationUlid(),$espace,$u,$titre,$contenu]);$id=(int)$pdo->lastInsertId();success('Sujet publié.',['id'=>$id]);}
 if($a==='reponse_forum'){$sujet=(int)($_POST['sujet_id']??0);$q=$pdo->prepare('SELECT espace_collaboratif_id,statut FROM sujets_forums WHERE id=?');$q->execute([$sujet]);$s=$q->fetch();if(!$s||$s['statut']!=='ouvert'||!membreEspace($pdo,(int)$s['espace_collaboratif_id'],$u,$org))reject('Sujet inaccessible.',403);$contenu=trim((string)($_POST['contenu']??''));if($contenu==='')reject('Réponse vide.');$pdo->prepare('INSERT INTO reponses_forums(identifiant_public,sujet_forum_id,auteur_utilisateur_id,contenu) VALUES(?,?,?,?)')->execute([communicationUlid(),$sujet,$u,$contenu]);success('Réponse publiée.');}
 if($a==='visio'){$titre=trim((string)($_POST['titre']??''));$fournisseur=(string)($_POST['fournisseur']??'jitsi');$lien=trim((string)($_POST['lien_reunion']??''));$debut=DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',(string)($_POST['debut']??''));$fin=DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',(string)($_POST['fin']??''));$dest=communicationResoudreCible($pdo,$u,$org,$role,(string)($_POST['cible']??''));if($titre===''||!$debut||!$fin||$fin<$debut||!filter_var($lien,FILTER_VALIDATE_URL)||!str_starts_with($lien,'https://')||!$dest||!in_array($fournisseur,['google_meet','zoom','microsoft_teams','jitsi','autre'],true))reject('Vérifiez la réunion et son lien HTTPS.');$pdo->beginTransaction();$pdo->prepare("INSERT INTO evenements_calendrier(identifiant_public,organisation_id,titre,type_evenement,debut,fin,lien_externe,statut,cree_par_utilisateur_id) VALUES(?,?,?,'visioconference',?,?,?,'confirme',?)")->execute([communicationUlid(),$org,$titre,$debut->format('Y-m-d H:i:s'),$fin->format('Y-m-d H:i:s'),$lien,$u]);$ev=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO reunions_visioconference(identifiant_public,evenement_calendrier_id,fournisseur,lien_reunion,code_acces,cree_par_utilisateur_id) VALUES(?,?,?,?,?,?)')->execute([communicationUlid(),$ev,$fournisseur,$lien,trim((string)($_POST['code_acces']??''))?:null,$u]);$q=$pdo->prepare('INSERT INTO participants_evenements(evenement_calendrier_id,utilisateur_id,statut_reponse,repondu_le) VALUES(?,?,?,?)');$q->execute([$ev,$u,'accepte',gmdate('Y-m-d H:i:s')]);foreach($dest as $d){$q->execute([$ev,$d,'invite',null]);communicationNotifier($pdo,$d,$org,'visioconference','Invitation visioconférence',$titre,$lien);}$pdo->commit();success('Visioconférence planifiée.');}
 if($a==='archiver'){$type=(string)($_POST['type']??'');$id=(int)($_POST['id']??0);$motif=mb_substr(trim((string)($_POST['motif']??'')),0,500);if($type==='conversation'){$q=$pdo->prepare("UPDATE conversations SET statut='archivee' WHERE id=? AND cree_par_utilisateur_id=?");$q->execute([$id,$u]);}elseif($type==='communication'){$q=$pdo->prepare("UPDATE communications_officielles SET statut='archivee' WHERE id=? AND publiee_par_utilisateur_id=?");$q->execute([$id,$u]);}elseif($type==='espace'){$q=$pdo->prepare("UPDATE espaces_collaboratifs SET statut='archive' WHERE id=? AND cree_par_utilisateur_id=?");$q->execute([$id,$u]);}elseif($type==='sujet_forum'){$q=$pdo->prepare("UPDATE sujets_forums SET statut='archive' WHERE id=? AND auteur_utilisateur_id=?");$q->execute([$id,$u]);}elseif($type==='notification'){$q=$pdo->prepare('UPDATE notifications SET archivee_le=UTC_TIMESTAMP(6) WHERE id=? AND utilisateur_id=?');$q->execute([$id,$u]);}else reject('Type d’archive invalide.');if(!$q->rowCount())reject('Archivage non autorisé.',403);$pdo->prepare("INSERT INTO journal_archivage_communications(type_ressource,ressource_id,action,motif,acteur_utilisateur_id) VALUES(?,?,'archive',?,?)")->execute([$type,$id,$motif?:null,$u]);success('Élément archivé.');}
 if($a==='preference'){$canal=(string)($_POST['canal']??'');if(!in_array($canal,['email','sms','push'],true))reject('Canal invalide.');$active=!empty($_POST['active']);$pdo->prepare('INSERT INTO preferences_notifications(utilisateur_id,type_evenement,canal,active) VALUES(?,\'*\',?,?) ON DUPLICATE KEY UPDATE active=VALUES(active)')->execute([$u,$canal,(int)$active]);success('Préférence enregistrée.');}
 reject('Action inconnue.');
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log((string)$e);reject($e instanceof RuntimeException?$e->getMessage():'Une erreur technique empêche l’opération.',500);}
