<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/permissions.php';require_once __DIR__.'/../../includes/communication-native.php';
header('Content-Type: application/json; charset=utf-8');
if(!communicationUtilisateurAutorise($pdo)){http_response_code(403);echo json_encode(['success'=>false,'message'=>'Accès refusé.']);exit;}
$u=(int)$_SESSION['user_id'];$org=communicationEtablissementId($pdo);$role=(string)($_SESSION['role_code']??'');$action=(string)($_GET['action']??'bootstrap');
try{
    if($action==='messages'){
        $id=(int)($_GET['conversation_id']??0);if(!communicationVerifierParticipant($pdo,$id,$u))throw new RuntimeException('Conversation inaccessible.');
        $q=$pdo->prepare("SELECT m.id,m.contenu,m.cree_le,m.modifie_le,m.statut,m.auteur_utilisateur_id,TRIM(CONCAT_WS(' ',x.prenom,x.postnom,x.nom)) auteur,(SELECT COUNT(*) FROM participants_conversations pc WHERE pc.conversation_id=m.conversation_id AND pc.utilisateur_id<>m.auteur_utilisateur_id AND pc.quitte_le IS NULL AND pc.dernier_message_lu_id>=m.id) lecteurs FROM messages m JOIN users x ON x.id=m.auteur_utilisateur_id WHERE m.conversation_id=? AND m.statut IN ('envoye','modifie') ORDER BY m.id");$q->execute([$id]);$items=$q->fetchAll();
        if($items){$ids=array_column($items,'id');$placeholders=implode(',',array_fill(0,count($ids),'?'));$q=$pdo->prepare("SELECT p.message_id,f.id,f.nom_original,f.type_mime,f.taille_octets FROM pieces_jointes_messages p JOIN fichiers f ON f.id=p.fichier_id WHERE p.message_id IN ($placeholders) AND f.archive_le IS NULL");$q->execute($ids);$pieces=[];foreach($q->fetchAll() as $p)$pieces[(int)$p['message_id']][]=$p;foreach($items as &$item)$item['pieces_jointes']=$pieces[(int)$item['id']]??[];unset($item);}
        $q=$pdo->prepare('SELECT id,objet,type_conversation,cree_par_utilisateur_id FROM conversations WHERE id=?');$q->execute([$id]);echo json_encode(['success'=>true,'data'=>['conversation'=>$q->fetch(),'items'=>$items]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;
    }
    $users=communicationDestinatairesAutorises($pdo,$u,(int)$org,$role);
    $q=$pdo->prepare("SELECT c.id,c.objet,c.type_conversation,c.cree_le,c.cree_par_utilisateur_id,(SELECT COUNT(*) FROM messages me WHERE me.conversation_id=c.id AND me.auteur_utilisateur_id=? AND me.statut IN ('envoye','modifie')) a_envoye,(SELECT COUNT(*) FROM messages mr WHERE mr.conversation_id=c.id AND mr.auteur_utilisateur_id<>? AND mr.statut IN ('envoye','modifie')) a_recu,(SELECT COUNT(*) FROM participants_conversations p2 WHERE p2.conversation_id=c.id AND p2.quitte_le IS NULL) participants,(SELECT m.contenu FROM messages m WHERE m.conversation_id=c.id AND m.statut IN ('envoye','modifie') ORDER BY m.id DESC LIMIT 1) apercu,(SELECT MAX(m.cree_le) FROM messages m WHERE m.conversation_id=c.id) activite_le,(SELECT COUNT(*) FROM messages m WHERE m.conversation_id=c.id AND m.id>COALESCE(pc.dernier_message_lu_id,0) AND m.auteur_utilisateur_id<>? AND m.statut IN ('envoye','modifie')) non_lus FROM conversations c JOIN participants_conversations pc ON pc.conversation_id=c.id WHERE pc.utilisateur_id=? AND pc.quitte_le IS NULL AND c.statut<>'archivee' ORDER BY COALESCE(activite_le,c.cree_le) DESC");$q->execute([$u,$u,$u,$u]);$conversations=$q->fetchAll();$q=$pdo->prepare("SELECT b.id,b.conversation_id,b.contenu,b.modifie_le,c.objet FROM brouillons_messages b JOIN conversations c ON c.id=b.conversation_id JOIN participants_conversations pc ON pc.conversation_id=c.id AND pc.utilisateur_id=b.utilisateur_id AND pc.quitte_le IS NULL WHERE b.utilisateur_id=? ORDER BY b.modifie_le DESC");$q->execute([$u]);$brouillons=$q->fetchAll();
    $q=$pdo->prepare("SELECT DISTINCT co.id,co.reference,co.type_communication,co.objet,co.contenu,co.priorite,co.accuse_reception_requis,co.publiee_le,co.publiee_par_utilisateur_id,d.lue_le,d.accusee_le,COALESCE(o.nom,'Administration nationale') emetteur FROM communications_officielles co LEFT JOIN destinataires_communications d ON d.communication_officielle_id=co.id AND d.utilisateur_id=? LEFT JOIN etablissements o ON o.id=co.organisation_emettrice_id WHERE (d.utilisateur_id=? OR co.publiee_par_utilisateur_id=?) AND co.statut='publiee' ORDER BY co.publiee_le DESC");$q->execute([$u,$u,$u]);$publications=$q->fetchAll();
    $q=$pdo->prepare("SELECT ev.id,ev.titre,ev.type_evenement,ev.debut,ev.fin,ev.lieu,ev.lien_externe,ev.cree_par_utilisateur_id,p.statut_reponse FROM evenements_calendrier ev JOIN participants_evenements p ON p.evenement_calendrier_id=ev.id WHERE p.utilisateur_id=? AND ev.fin>=UTC_TIMESTAMP()-INTERVAL 30 DAY AND ev.statut<>'annule' ORDER BY ev.debut");$q->execute([$u]);$events=$q->fetchAll();
    $q=$pdo->prepare('SELECT id,titre,contenu,lien_action,priorite,lue_le,cree_le FROM notifications WHERE utilisateur_id=? AND archivee_le IS NULL ORDER BY cree_le DESC LIMIT 100');$q->execute([$u]);$notifications=$q->fetchAll();
    echo json_encode(['success'=>true,'data'=>['users'=>$users,'conversations'=>$conversations,'brouillons'=>$brouillons,'publications'=>$publications,'events'=>$events,'notifications'=>$notifications,'me'=>$u,'academic_context'=>communicationContexteAcademique($pdo,$u),'isolation'=>true]],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){error_log((string)$e);http_response_code(500);echo json_encode(['success'=>false,'message'=>'Chargement impossible. Vérifiez que la migration d’isolation est appliquée.']);}
