<?php
declare(strict_types=1);
require_once __DIR__.'/../../config/config.php';require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/auth.php';require_once __DIR__.'/../../includes/permissions.php';require_once __DIR__.'/../../includes/communication-native.php';header('Content-Type: application/json; charset=utf-8');requireCommunicationRole();
function gestionOk(string $m,array $d=[]):never{echo json_encode(['success'=>true,'message'=>$m,'data'=>$d],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}function gestionRefus(string $m,int $c=422):never{http_response_code($c);echo json_encode(['success'=>false,'message'=>$m],JSON_UNESCAPED_UNICODE);exit;}
if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??'')))gestionRefus('Session expirée.',419);$action=(string)($_POST['action']??'');$type=(string)($_POST['type']??'');$id=(int)($_POST['id']??0);$u=(int)$_SESSION['user_id'];$org=communicationEtablissementId($pdo);$super=communicationEstSuperAdministrateur();
function ligneProprietaire(PDO $pdo,string $type,int $id,int $u,bool $super):array{
 if($type==='visioconference'){$q=$pdo->prepare('SELECT rv.*,ev.titre,ev.debut,ev.fin,ev.statut evenement_statut,ev.cree_par_utilisateur_id FROM reunions_visioconference rv JOIN evenements_calendrier ev ON ev.id=rv.evenement_calendrier_id WHERE rv.id=?'.($super?'':' AND ev.cree_par_utilisateur_id=?').' LIMIT 1');$q->execute($super?[$id]:[$id,$u]);return$q->fetch()?:[];}
 $regles=[
  'conversation'=>['conversations','cree_par_utilisateur_id'], 'message'=>['messages','auteur_utilisateur_id'],
  'communication'=>['communications_officielles','publiee_par_utilisateur_id'], 'evenement'=>['evenements_calendrier','cree_par_utilisateur_id'],
  'espace'=>['espaces_collaboratifs','cree_par_utilisateur_id'], 'sujet_forum'=>['sujets_forums','auteur_utilisateur_id'],
  'reponse_forum'=>['reponses_forums','auteur_utilisateur_id']
 ];if(!isset($regles[$type]))return [];[$table,$col]=$regles[$type];$q=$pdo->prepare("SELECT * FROM $table WHERE id=?".($super?'':" AND $col=?").' LIMIT 1');$q->execute($super?[$id]:[$id,$u]);return $q->fetch()?:[];
}
try{
 if($action==='modifier'){
  $avant=ligneProprietaire($pdo,$type,$id,$u,$super);if(!$avant)gestionRefus('Modification non autorisée.',403);$apres=[];
  if($type==='message'){$contenu=trim((string)($_POST['contenu']??''));if($contenu==='')gestionRefus('Le message ne peut pas être vide.');$pdo->prepare("UPDATE messages SET contenu=?,statut='modifie',modifie_le=UTC_TIMESTAMP(6) WHERE id=?")->execute([$contenu,$id]);$apres=['contenu'=>$contenu];}
  elseif($type==='conversation'){$objet=trim((string)($_POST['objet']??''));if($objet==='')gestionRefus('Objet obligatoire.');$pdo->prepare('UPDATE conversations SET objet=? WHERE id=?')->execute([$objet,$id]);$apres=['objet'=>$objet];}
  elseif($type==='communication'){$objet=trim((string)($_POST['objet']??''));$contenu=trim((string)($_POST['contenu']??''));if($objet===''||$contenu==='')gestionRefus('Objet et contenu obligatoires.');$pdo->prepare('UPDATE communications_officielles SET objet=?,contenu=? WHERE id=?')->execute([$objet,$contenu,$id]);$apres=['objet'=>$objet,'contenu'=>$contenu];}
  elseif($type==='evenement'||$type==='visioconference'){$titre=trim((string)($_POST['titre']??''));$debut=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',(string)($_POST['debut']??''));$fin=DateTimeImmutable::createFromFormat('Y-m-d\TH:i',(string)($_POST['fin']??''));if($titre===''||!$debut||!$fin||$fin<$debut)gestionRefus('Période invalide.');$evenementId=$type==='visioconference'?(int)$avant['evenement_calendrier_id']:$id;$pdo->prepare('UPDATE evenements_calendrier SET titre=?,debut=?,fin=? WHERE id=?')->execute([$titre,$debut->format('Y-m-d H:i:s'),$fin->format('Y-m-d H:i:s'),$evenementId]);$apres=['titre'=>$titre,'debut'=>$debut->format(DATE_ATOM),'fin'=>$fin->format(DATE_ATOM)];if($type==='visioconference'){$lien=trim((string)($_POST['lien_reunion']??''));$fournisseur=(string)($_POST['fournisseur']??'jitsi');if(!filter_var($lien,FILTER_VALIDATE_URL)||!str_starts_with($lien,'https://')||!in_array($fournisseur,['google_meet','zoom','microsoft_teams','jitsi','autre'],true))gestionRefus('Lien HTTPS ou fournisseur invalide.');$code=trim((string)($_POST['code_acces']??''));$pdo->prepare('UPDATE reunions_visioconference SET fournisseur=?,lien_reunion=?,code_acces=? WHERE id=?')->execute([$fournisseur,$lien,$code?:null,$id]);$apres+=['fournisseur'=>$fournisseur,'lien_reunion'=>$lien,'code_acces'=>$code];}}
  elseif($type==='espace'){$nom=trim((string)($_POST['nom']??''));$description=trim((string)($_POST['description']??''));if($nom==='')gestionRefus('Nom obligatoire.');$pdo->prepare('UPDATE espaces_collaboratifs SET nom=?,description=? WHERE id=?')->execute([$nom,$description,$id]);$apres=['nom'=>$nom,'description'=>$description];}
  elseif($type==='sujet_forum'){$titre=trim((string)($_POST['titre']??''));$contenu=trim((string)($_POST['contenu']??''));if($titre===''||$contenu==='')gestionRefus('Sujet incomplet.');$pdo->prepare('UPDATE sujets_forums SET titre=?,contenu=? WHERE id=?')->execute([$titre,$contenu,$id]);$apres=['titre'=>$titre,'contenu'=>$contenu];}
  elseif($type==='reponse_forum'){$contenu=trim((string)($_POST['contenu']??''));if($contenu==='')gestionRefus('Réponse vide.');$pdo->prepare("UPDATE reponses_forums SET contenu=?,statut='modifiee',modifie_le=UTC_TIMESTAMP(6) WHERE id=?")->execute([$contenu,$id]);$apres=['contenu'=>$contenu];}
  else gestionRefus('Type non modifiable.');communicationHistorique($pdo,$type,$id,$avant,$apres,$u);gestionOk('Modification enregistrée.');
 }
 if($action==='supprimer'){
  $avant=ligneProprietaire($pdo,$type,$id,$u,$super);if(!$avant&&$type!=='notification')gestionRefus('Suppression non autorisée.',403);$etat=(string)($avant['statut']??'actif');$libelle=(string)($avant['objet']??$avant['titre']??$avant['nom']??mb_substr((string)($avant['contenu']??'Élément'),0,120));
  if($type==='conversation')$pdo->prepare("UPDATE conversations SET statut='archivee' WHERE id=?")->execute([$id]);elseif($type==='message')$pdo->prepare("UPDATE messages SET statut='retire',retire_le=UTC_TIMESTAMP(6) WHERE id=?")->execute([$id]);elseif($type==='communication')$pdo->prepare("UPDATE communications_officielles SET statut='retiree' WHERE id=?")->execute([$id]);elseif($type==='evenement')$pdo->prepare("UPDATE evenements_calendrier SET statut='annule' WHERE id=?")->execute([$id]);elseif($type==='visioconference'){$pdo->prepare("UPDATE reunions_visioconference SET statut='annulee' WHERE id=?")->execute([$id]);$pdo->prepare("UPDATE evenements_calendrier SET statut='annule' WHERE id=?")->execute([(int)$avant['evenement_calendrier_id']]);}elseif($type==='espace')$pdo->prepare("UPDATE espaces_collaboratifs SET statut='archive' WHERE id=?")->execute([$id]);elseif($type==='sujet_forum')$pdo->prepare("UPDATE sujets_forums SET statut='archive' WHERE id=?")->execute([$id]);elseif($type==='reponse_forum')$pdo->prepare("UPDATE reponses_forums SET statut='retiree' WHERE id=?")->execute([$id]);elseif($type==='notification'){$q=$pdo->prepare('SELECT * FROM notifications WHERE id=? AND utilisateur_id=?');$q->execute([$id,$u]);$avant=$q->fetch()?:[];if(!$avant)gestionRefus('Notification inaccessible.',403);$libelle=(string)$avant['titre'];$etat='active';$pdo->prepare('UPDATE notifications SET archivee_le=UTC_TIMESTAMP(6) WHERE id=? AND utilisateur_id=?')->execute([$id,$u]);}else gestionRefus('Type non supprimable.');communicationMettreCorbeille($pdo,$type,$id,$libelle,$etat,$avant,$u);gestionOk('Élément déplacé dans la corbeille.');
 }
 if($action==='restaurer'){$corbeille=(int)($_POST['corbeille_id']??0);$q=$pdo->prepare('SELECT * FROM corbeille_communications WHERE id=? AND restaure_le IS NULL'.($super?'':' AND supprime_par_utilisateur_id=?').' LIMIT 1');$q->execute($super?[$corbeille]:[$corbeille,$u]);$c=$q->fetch();if(!$c)gestionRefus('Élément de corbeille inaccessible.',403);$t=(string)$c['type_ressource'];$rid=(int)$c['ressource_id'];$etat=(string)($c['etat_avant']?:'actif');$donnees=json_decode((string)($c['donnees']??'{}'),true)?:[];if($t==='conversation')$pdo->prepare('UPDATE conversations SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='message')$pdo->prepare('UPDATE messages SET statut=?,retire_le=NULL WHERE id=?')->execute([$etat,$rid]);elseif($t==='communication')$pdo->prepare('UPDATE communications_officielles SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='evenement')$pdo->prepare('UPDATE evenements_calendrier SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='visioconference'){$pdo->prepare("UPDATE reunions_visioconference SET statut='planifiee' WHERE id=?")->execute([$rid]);$pdo->prepare("UPDATE evenements_calendrier SET statut='confirme' WHERE id=?")->execute([(int)($donnees['evenement_calendrier_id']??0)]);}elseif($t==='espace')$pdo->prepare('UPDATE espaces_collaboratifs SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='sujet_forum')$pdo->prepare('UPDATE sujets_forums SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='reponse_forum')$pdo->prepare('UPDATE reponses_forums SET statut=? WHERE id=?')->execute([$etat,$rid]);elseif($t==='notification')$pdo->prepare('UPDATE notifications SET archivee_le=NULL WHERE id=? AND utilisateur_id=?')->execute([$rid,$u]);else gestionRefus('Restauration non prise en charge.');$pdo->prepare('UPDATE corbeille_communications SET restaure_le=UTC_TIMESTAMP(6) WHERE id=?')->execute([$corbeille]);gestionOk('Élément restauré.');}
 if($action==='configuration'){
  if(!$super)gestionRefus('Configuration réservée au super-administrateur.',403);$canal=(string)($_POST['canal']??'');if(!in_array($canal,['smtp','sms','push'],true))gestionRefus('Canal invalide.');$secret=trim((string)($_POST['secret']??''));$q=$pdo->prepare('SELECT id,secret_chiffre FROM configurations_canaux_communication WHERE organisation_id <=> ? AND canal=?');$q->execute([$org,$canal]);$existante=$q->fetch()?:[];$secretChiffre=$secret!==''?communicationChiffrerSecret($secret):(string)($existante['secret_chiffre']??'');$params=trim((string)($_POST['parametres']??''));if($params!==''&&json_decode($params,true)===null)gestionRefus('Les paramètres JSON sont invalides.');$valeurs=[$org,$canal,(int)!empty($_POST['actif']),trim((string)($_POST['fournisseur']??''))?:null,trim((string)($_POST['hote']??''))?:null,(int)($_POST['port']??0)?:null,trim((string)($_POST['nom_utilisateur']??''))?:null,$secretChiffre?:null,trim((string)($_POST['adresse_expediteur']??''))?:null,trim((string)($_POST['nom_expediteur']??''))?:null,$params?:null,$u];$pdo->prepare('INSERT INTO configurations_canaux_communication(organisation_id,canal,actif,fournisseur,hote,port,nom_utilisateur,secret_chiffre,adresse_expediteur,nom_expediteur,parametres,modifie_par_utilisateur_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE actif=VALUES(actif),fournisseur=VALUES(fournisseur),hote=VALUES(hote),port=VALUES(port),nom_utilisateur=VALUES(nom_utilisateur),secret_chiffre=VALUES(secret_chiffre),adresse_expediteur=VALUES(adresse_expediteur),nom_expediteur=VALUES(nom_expediteur),parametres=VALUES(parametres),modifie_par_utilisateur_id=VALUES(modifie_par_utilisateur_id)')->execute($valeurs);gestionOk('Configuration enregistrée. Le secret reste masqué.');
 }
 gestionRefus('Action inconnue.');
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log((string)$e);gestionRefus($e instanceof RuntimeException?$e->getMessage():'Une erreur technique empêche l’opération.',500);}
