<?php
if(PHP_SAPI!=='cli')exit("Terminal uniquement.\n");
$root=realpath(__DIR__.'/..');$file=$root.'/includes/app-header.php';if(!is_file($file))exit("includes/app-header.php introuvable.\n");
$src=file_get_contents($file);$backup=$file.'.before-host-structure.bak';if(!is_file($backup))copy($file,$backup);
if(strpos($src,"require_once __DIR__.'/host-structure.php';")===false){$needle="require_once __DIR__.'/academic-structure.php';";$src=strpos($src,$needle)!==false?str_replace($needle,$needle."\nrequire_once __DIR__.'/host-structure.php';",$src):str_replace("require_once __DIR__.'/auth.php';","require_once __DIR__.'/auth.php';\nrequire_once __DIR__.'/host-structure.php';",$src);}
if(strpos($src,'$hostDepartmentEnabled=')===false){$needle='$host=contextHostEnabled();';$insert=$needle."\n\$hostStructureCfg=(\$host&&(\$hostStructureEid=(int)(\$_SESSION['etablissement_id']??0))>0)?hostStructureConfig(\$pdo,\$hostStructureEid):hostStructureDefaults();\n\$hostDepartmentEnabled=hostStructureEnabled(\$hostStructureCfg,'DEPARTEMENT');\n\$hostDepartmentLabel=hostStructureLabel(\$hostStructureCfg,'DEPARTEMENT',true,'Départements');\n\$hostServiceLabel=hostStructureLabel(\$hostStructureCfg,'SERVICE',true,'Services');\n\$hostUnitLabel=hostStructureLabel(\$hostStructureCfg,'UNITE',true,'Unités');\n\$hostServicesMenuLabel=trim((hostStructureEnabled(\$hostStructureCfg,'SERVICE')?\$hostServiceLabel:'').(hostStructureEnabled(\$hostStructureCfg,'SERVICE')&&hostStructureEnabled(\$hostStructureCfg,'UNITE')?' / ':'').(hostStructureEnabled(\$hostStructureCfg,'UNITE')?\$hostUnitLabel:''));";$src=str_replace($needle,$insert,$src);}
$one="stagiaNav(BASE_URL.'/views/espace-hopital/services-unites.php','bi-diagram-3','Services / unités','hospital-services',\$activePage);";$rep="if(\$hostDepartmentEnabled) stagiaNav(BASE_URL.'/views/espace-hopital/departements.php','bi-diagram-2',\$hostDepartmentLabel,'hospital-departments',\$activePage);\n        if(\$hostServicesMenuLabel!=='') stagiaNav(BASE_URL.'/views/espace-hopital/services-unites.php','bi-diagram-3',\$hostServicesMenuLabel,'hospital-services',\$activePage);";$src=str_replace($one,$rep,$src);
$multi="stagiaNav(\n        BASE_URL.'/views/espace-hopital/services-unites.php',\n        'bi-diagram-3',\n        'Services / unités',\n        'hospital-services',\n        \$activePage\n    );";$rep2="if(\$hostDepartmentEnabled) stagiaNav(BASE_URL.'/views/espace-hopital/departements.php','bi-diagram-2',\$hostDepartmentLabel,'hospital-departments',\$activePage);\n    if(\$hostServicesMenuLabel!=='') stagiaNav(BASE_URL.'/views/espace-hopital/services-unites.php','bi-diagram-3',\$hostServicesMenuLabel,'hospital-services',\$activePage);";$src=str_replace($multi,$rep2,$src);
if(strpos($src,"'host-structure-config'")===false)$src=str_replace('$adminPages=[',"\$adminPages=[\n    'host-structure-config',",$src);
$admin="\n        if(\$host && \$role==='ADMIN_ACCUEIL' && contextPermission('host.manage')) \$localAdminItems[]=[BASE_URL.'/views/administration-etablissement/structure-accueil.php','bi-diagram-3','Structure d’accueil','host-structure-config'];\n";
$src=preg_replace('/(\$localAdminItems=\[\];)(?!\s*if\(\$host && \$role===\'ADMIN_ACCUEIL\')/',"$1".$admin,$src);
file_put_contents($file,$src);echo "Menu Structure d'accueil installé.\nSauvegarde : includes/app-header.php.before-host-structure.bak\n";
