<?php
declare(strict_types=1);
require_once __DIR__.'/../../../config/config.php';require_once __DIR__.'/../../../config/database.php';require_once __DIR__.'/../../../includes/auth.php';require_once __DIR__.'/../../../includes/admin-scope.php';
if(!estSuperAdminPrincipal()){http_response_code(403);exit('Accès réservé au super administrateur principal.');}if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$pageTitle='Rattachements ministériels';$activePage='admin-ministeres';require_once __DIR__.'/../../../includes/app-header.php';
?>
<main class="dashboard-content"><div class="stagia-page-head"><div><h1>Rattachements ministériels</h1><p>Définissez précisément les organisations visibles par chaque ministère.</p></div></div>
<div class="stagia-list-card p-4"><form id="form"><input type="hidden" name="csrf" value="<?=htmlspecialchars($_SESSION['csrf'])?>"><div class="mb-4"><label class="form-label">Ministère</label><select class="form-select" name="ministere_id" id="ministere" required></select></div><label class="form-label">Organisations rattachées</label><div id="organisations" class="row g-3"></div><div class="mt-4 text-end"><button class="btn btn-primary-stagia"><i class="bi bi-check-lg me-1"></i>Enregistrer les rattachements</button></div></form></div></main>
<script>document.addEventListener('DOMContentLoaded',()=>{const B='<?=BASE_URL?>',E=STAGIA.escape,$=id=>document.getElementById(id);let data;function draw(){const mid=Number($('ministere').value),selected=new Set(data.liens.filter(x=>Number(x.ministere_etablissement_id)===mid&&Number(x.actif)===1).map(x=>Number(x.organisation_etablissement_id)));$('organisations').innerHTML=data.organisations.map(x=>`<div class="col-md-6 col-xl-4"><label class="border rounded-3 p-3 d-flex gap-2 h-100"><input class="form-check-input" type="checkbox" name="organisation_ids[]" value="${x.id}" ${selected.has(Number(x.id))?'checked':''}><span><strong>${E(x.nom)}</strong><small class="d-block text-muted">${E(x.type_etablissement)} · ${E(x.province||'Province non renseignée')}</small></span></label></div>`).join('')}async function load(){const r=await STAGIA.request(B+'/actions/admin/ministeres/organisations.php');data=r.data;$('ministere').innerHTML='<option value="">Sélectionner…</option>'+data.ministeres.map(x=>`<option value="${x.id}">${E(x.nom)}</option>`).join('');draw()}$('ministere').onchange=draw;$('form').onsubmit=async e=>{e.preventDefault();try{const r=await STAGIA.post(B+'/actions/admin/ministeres/organisations.php',new FormData(e.target));STAGIA.toast(r.message);await load()}catch(x){STAGIA.toast(x.message,'danger')}};load()});</script>
<?php require_once __DIR__.'/../../../includes/app-footer.php'; ?>
