<?php
require_once __DIR__.'/../../config/config.php';
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/auth.php';
requireRole(['STAGIAIRE']);
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));
$pageTitle='Mes tâches';$activePage='student-tasks';
require_once __DIR__.'/../../includes/app-header.php';
?>
<style>
.task-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.task-kpi,.student-task{background:#fff;border:1px solid #e7ebf0;border-radius:14px}.task-kpi{padding:16px}.task-kpi small{display:block;color:#64748b;font-size:11px;text-transform:uppercase}.task-kpi strong{font-size:26px}.student-task{padding:18px}.progress-main{height:10px}.task-meta{font-size:12px;color:#64748b}@media(max-width:1000px){.task-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.task-grid{grid-template-columns:1fr}}
</style>
<main class="dashboard-content">
<div class="stagia-page-head"><div><h1>Mes tâches</h1><p>Suivez vos activités assignées et votre progression de stage.</p></div></div>
<div class="student-task mb-4"><div class="d-flex justify-content-between align-items-center"><div><strong>Progression validée</strong><small class="d-block text-muted">Une tâche compte dans la progression après validation de l'encadreur.</small></div><strong class="fs-4" id="progressPct">0%</strong></div><div class="progress progress-main mt-3"><div id="progressBar" class="progress-bar" style="width:0%"></div></div></div>
<div class="task-grid mb-4"><div class="task-kpi"><small>Total</small><strong id="kTotal">0</strong></div><div class="task-kpi"><small>À faire</small><strong id="kTodo">0</strong></div><div class="task-kpi"><small>En cours</small><strong id="kDoing">0</strong></div><div class="task-kpi"><small>À revoir</small><strong id="kReview">0</strong></div><div class="task-kpi"><small>Validées</small><strong id="kValid">0</strong></div></div>
<div class="d-flex justify-content-end mb-3"><select id="statusFilter" class="form-select" style="max-width:240px"><option value="">Tous les statuts</option><option value="A_FAIRE">À faire</option><option value="EN_COURS">En cours</option><option value="TERMINEE">Terminées</option><option value="A_REVOIR">À revoir</option><option value="VALIDEE">Validées</option><option value="ANNULEE">Annulées</option></select></div>
<div id="taskList"><div class="student-task text-center text-muted py-5">Chargement...</div></div>
</main>
<script>
document.addEventListener('DOMContentLoaded',()=>{
const BASE='<?=BASE_URL?>',CSRF='<?=htmlspecialchars($_SESSION['csrf'])?>',$=id=>document.getElementById(id),esc=STAGIA.escape;
const labels={A_FAIRE:'À faire',EN_COURS:'En cours',TERMINEE:'Terminée — en attente de validation',A_REVOIR:'À revoir',VALIDEE:'Validée',ANNULEE:'Annulée'};
const classes={A_FAIRE:'bg-secondary-subtle text-secondary',EN_COURS:'bg-primary-subtle text-primary',TERMINEE:'bg-info-subtle text-info',A_REVOIR:'bg-warning-subtle text-warning',VALIDEE:'bg-success-subtle text-success',ANNULEE:'bg-danger-subtle text-danger'};
function dateFr(v){if(!v)return '—';const p=String(v).slice(0,10).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:v;}
function actions(x){if(x.statut==='A_FAIRE')return `<button class="btn btn-sm btn-primary-stagia act" data-id="${x.id}" data-action="START"><i class="bi bi-play-fill me-1"></i>Démarrer</button>`;if(x.statut==='A_REVOIR')return `<button class="btn btn-sm btn-warning act" data-id="${x.id}" data-action="START"><i class="bi bi-arrow-repeat me-1"></i>Reprendre</button>`;if(x.statut==='EN_COURS')return `<button class="btn btn-sm btn-success act" data-id="${x.id}" data-action="COMPLETE"><i class="bi bi-check-lg me-1"></i>Déclarer terminée</button>`;return '';}
function render(items){$('taskList').innerHTML=items.length?items.map(x=>`<div class="student-task mb-2"><div class="d-flex justify-content-between gap-3 flex-wrap"><div class="flex-grow-1"><div class="d-flex align-items-center gap-2 flex-wrap"><h5 class="mb-0">${esc(x.titre)}</h5><span class="badge ${classes[x.statut]||'bg-light text-dark'}">${esc(labels[x.statut]||x.statut)}</span><span class="badge bg-light text-dark border">${esc(x.priorite)}</span></div><div class="task-meta mt-2">${x.host_name?`<i class="bi bi-hospital me-1"></i>${esc(x.host_name)} · `:''}${x.unit_name?`${esc(x.unit_name)} · `:''}Échéance : ${dateFr(x.date_echeance)}</div>${x.plan_item_title?`<div class="task-meta mt-1"><i class="bi bi-list-check me-1"></i>${esc(x.plan_item_title)}</div>`:''}${x.description?`<p class="mt-2 mb-1">${esc(x.description)}</p>`:''}${x.commentaire_encadreur?`<div class="alert alert-warning py-2 mt-2 mb-1"><strong>Encadreur :</strong> ${esc(x.commentaire_encadreur)}</div>`:''}${x.commentaire_stagiaire?`<div class="small mt-2"><strong>Mon commentaire :</strong> ${esc(x.commentaire_stagiaire)}</div>`:''}</div><div class="d-flex gap-1 align-items-start">${actions(x)}${!['VALIDEE','ANNULEE'].includes(x.statut)?`<button class="btn btn-sm btn-outline-secondary comment" data-id="${x.id}"><i class="bi bi-chat-left-text"></i></button>`:''}</div></div></div>`).join(''):'<div class="student-task text-center text-muted py-5">Aucune tâche.</div>';document.querySelectorAll('.act').forEach(b=>b.onclick=()=>act(Number(b.dataset.id),b.dataset.action));document.querySelectorAll('.comment').forEach(b=>b.onclick=()=>saveComment(Number(b.dataset.id)));}
async function load(){const q=$('statusFilter').value?`?status=${encodeURIComponent($('statusFilter').value)}`:'';try{const r=await STAGIA.request(BASE+'/actions/espace-etudiant/task-list.php'+q);const s=r.data.stats||{},p=Number(r.data.progress)||0;$('kTotal').textContent=s.total||0;$('kTodo').textContent=s.a_faire||0;$('kDoing').textContent=s.en_cours||0;$('kReview').textContent=s.a_revoir||0;$('kValid').textContent=s.validees||0;$('progressPct').textContent=p+'%';$('progressBar').style.width=Math.max(0,Math.min(100,p))+'%';render(r.data.items||[]);}catch(e){STAGIA.toast(e.message,'danger');}}
async function act(id,action){const label=action==='COMPLETE'?'Commentaire / preuve de réalisation (facultatif) :':'Commentaire (facultatif) :';const comment=prompt(label)||'';if(action==='COMPLETE'&&!STAGIA.confirm("Déclarer cette tâche terminée et l'envoyer à l'encadreur ?"))return;const fd=new FormData();fd.append('csrf',CSRF);fd.append('id',id);fd.append('action',action);fd.append('commentaire',comment);try{const r=await STAGIA.post(BASE+'/actions/espace-etudiant/task-status.php',fd);STAGIA.toast(r.message);await load();}catch(e){STAGIA.toast(e.message,'danger');}}
async function saveComment(id){const comment=prompt('Votre commentaire :')||'';if(!comment.trim())return;const fd=new FormData();fd.append('csrf',CSRF);fd.append('id',id);fd.append('action','COMMENT');fd.append('commentaire',comment);try{const r=await STAGIA.post(BASE+'/actions/espace-etudiant/task-status.php',fd);STAGIA.toast(r.message);await load();}catch(e){STAGIA.toast(e.message,'danger');}}
$('statusFilter').onchange=load;load();
});
</script>
<?php require_once __DIR__.'/../../includes/app-footer.php'; ?>
